import { ConflictException, Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { createHash } from 'crypto';
import { Executive, MonthlyMapping, MonthlyTarget, TargetVersion, WeeklyMapping, WeeklyTarget } from '../../database/schemas/domain.schemas';
import { TargetsService } from '../targets/targets.service';
@Injectable()
export class PlanningService {
  constructor(@InjectModel(Executive.name) private executives:Model<Executive>,@InjectModel(MonthlyMapping.name) private monthlyMappings:Model<MonthlyMapping>,@InjectModel(WeeklyMapping.name) private weeklyMappings:Model<WeeklyMapping>,@InjectModel(WeeklyTarget.name) private weeklyTargets:Model<WeeklyTarget>,@InjectModel(MonthlyTarget.name) private monthlyTargets:Model<MonthlyTarget>,@InjectModel('WeeklySnapshot') private weeklySnapshots:Model<any>,@InjectModel('MonthlySnapshot') private monthlySnapshots:Model<any>,private targets:TargetsService){}
  async createWeekly(date=new Date(),userId?:string){const week=this.monday(date);if(await this.weeklySnapshots.exists({period:this.dateKey(week)})) throw new ConflictException('Weekly snapshot already exists'); const executives=await this.executives.find({active:true}).lean(); const mappings=[];const targets=[];for(const executive of executives){const target=await this.targets.resolve(executive.source,executive.tenurity,week);mappings.push({weekStart:week,month:this.monthKey(week),executiveId:executive._id,source:executive.source,tenurity:executive.tenurity,managerId:executive.managerId,version:1,immutable:true});targets.push({weekStart:week,executiveId:executive._id,targetVersionId:(target as any)._id,revenue:target.revenue,metrics:{login:target.login,demo:target.demo,license:target.license,proPlatform:target.proPlatform,arpl:target.arpl},immutable:true});} if(mappings.length){await this.weeklyMappings.insertMany(mappings,{ordered:false});await this.weeklyTargets.insertMany(targets,{ordered:false});} const payload={mappings,targets};await this.weeklySnapshots.create({period:this.dateKey(week),version:1,checksum:this.checksum(payload),payload,createdBy:userId});return{period:this.dateKey(week),executives:mappings.length};}
  async createMonthly(date=new Date(),userId?:string){const month=this.monthKey(date);if(await this.monthlySnapshots.exists({period:month}))throw new ConflictException('Monthly snapshot already exists');const executives=await this.executives.find({active:true}).lean();const mappings=executives.map((e)=>({month,executiveId:e._id,source:e.source,tenurity:e.tenurity,managerId:e.managerId,version:1,immutable:true}));if(mappings.length)await this.monthlyMappings.insertMany(mappings,{ordered:false});const managerByExecutive=new Map(executives.map(e=>[String(e._id),e.managerId]));const weekly=await this.weeklyTargets.aggregate([{ $match:{weekStart:{$gte:new Date(`${month}-01T00:00:00.000Z`),$lt:this.nextMonth(month)}}},{ $group:{_id:'$executiveId',revenue:{$sum:'$revenue'},login:{$sum:'$metrics.login'},demo:{$sum:'$metrics.demo'},license:{$sum:'$metrics.license'},proPlatform:{$sum:'$metrics.proPlatform'}}}]);const monthly=weekly.map((x)=>({month,executiveId:x._id,managerId:managerByExecutive.get(String(x._id)),revenue:x.revenue,metrics:{login:x.login,demo:x.demo,license:x.license,proPlatform:x.proPlatform},immutable:true}));if(monthly.length)await this.monthlyTargets.insertMany(monthly,{ordered:false});const payload={mappings,targets:monthly};await this.monthlySnapshots.create({period:month,version:1,checksum:this.checksum(payload),payload,createdBy:userId});return{period:month,executives:mappings.length};}
  listWeekly(week:string){return this.weeklyMappings.find({weekStart:new Date(`${week}T00:00:00.000Z`)}).populate('executiveId').lean();}
  private monday(value:Date){const d=new Date(value);const day=d.getUTCDay();d.setUTCDate(d.getUTCDate()-(day===0?6:day-1));d.setUTCHours(0,0,0,0);return d;} private dateKey(d:Date){return d.toISOString().slice(0,10);} private monthKey(d:Date){return d.toISOString().slice(0,7);} private nextMonth(month:string){const [y,m]=month.split('-').map(Number);return new Date(Date.UTC(y,m,1));} private checksum(value:unknown){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
}
