'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createColumnHelper } from '@tanstack/react-table';
import { Plus, X } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { api, Target, TargetInput } from '@/lib/api';
import { money } from '@/lib/utils';
import { DataTable } from '@/components/data-table';

const column = createColumnHelper<Target>();
const columns = [column.accessor('source',{header:'Source'}),column.accessor('tenurity',{header:'Tenurity'}),column.accessor('version',{header:'Version'}),column.accessor('effectiveFrom',{header:'Effective from'}),column.accessor('effectiveTo',{header:'Effective till',cell:value=>value.getValue()??'Current'}),column.accessor('revenue',{header:'Revenue',cell:value=>money(value.getValue())}),column.accessor('login',{header:'Login'}),column.accessor('demo',{header:'Demo'}),column.accessor('license',{header:'License'}),column.accessor('status',{header:'Status'})];
const blank: TargetInput = { source: '', tenurity: 'M0', effectiveFrom: new Date().toISOString().slice(0,10), revenue: 0, login: 0, demo: 0, license: 0, proPlatform: 0, arpl: 0 };

export default function Page(){const[open,setOpen]=useState(false);const[form,setForm]=useState<TargetInput>(blank);const queryClient=useQueryClient();const targets=useQuery({queryKey:['targets'],queryFn:()=>api<Target[]>('/targets')});const create=useMutation({mutationFn:(input:TargetInput)=>api('/targets/versions',{method:'POST',body:JSON.stringify(input)}),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:['targets']});setOpen(false);setForm(blank);}});function submit(event:FormEvent){event.preventDefault();create.mutate(form);}return <><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Target versions</h2><p className="text-slate-500">Effective-dated targets by source and tenurity. New versions close the previous active version.</p></div><button className="btn gap-2" onClick={()=>setOpen(true)}><Plus size={17}/> New target version</button></div>{targets.error&&<p className="mb-4 text-red-700">{targets.error.message}</p>}<DataTable data={targets.data??[]} columns={columns}/>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h3 className="text-xl font-bold">Create target version</h3><p className="text-sm text-slate-500">The previous matching source/tenurity version becomes inactive automatically.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">Source<input required className="mt-1 w-full" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label className="text-sm font-medium">Tenurity<select className="mt-1 w-full" value={form.tenurity} onChange={e=>setForm({...form,tenurity:e.target.value})}><option>M0</option><option>M1</option><option>M1+</option></select></label><label className="text-sm font-medium">Effective from<input required type="date" className="mt-1 w-full" value={form.effectiveFrom} onChange={e=>setForm({...form,effectiveFrom:e.target.value})}/></label>{(['revenue','login','demo','license','proPlatform','arpl'] as const).map(key=><label key={key} className="text-sm font-medium">{key==='proPlatform'?'Pro Platform':key[0].toUpperCase()+key.slice(1)}<input required min="0" step="0.01" type="number" className="mt-1 w-full" value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/></label>)}</div>{create.error&&<p className="mt-4 text-sm text-red-700">{create.error.message}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn" disabled={create.isPending}>{create.isPending?'Creating…':'Create version'}</button></div></form></div>}</>}
