var AGENT_CONNECTION_ALIASES={datamonth:'dataMonth',month:'dataMonth',employeeid:'employeeId',executivename:'name',name:'name',agentname:'name',email:'email',workemail:'email',doj:'doj',dateofjoining:'doj',manager:'manager',manageremail:'manager',reportingmanager:'manager'};

function agentConnection_(){var excluded={};Object.keys(PLATFORM.SHEETS).forEach(function(name){excluded[name]=true;});delete excluded.agentDataDump;return resolveSheetConnection_({label:'executive identity',spreadsheetKey:'agentSpreadsheetId',sheetKey:'agentSheetName',aliases:AGENT_CONNECTION_ALIASES,required:['employeeId','name','email','doj'],candidates:['agentDataDump','Connected Sheet 1','bigQueryAgentDump'],exclude:excluded});}
function configureAgentSheet_(context,payload){requireRole_(context,['ADMIN']);var spreadsheetId=normalizeSpreadsheetId_(payload.spreadsheetId);var sheetName=String(payload.sheetName||'').trim();if(!spreadsheetId||!sheetName)throw apiError_(400,'Executive identity spreadsheet and tab name are required.');var sheet=SpreadsheetApp.openById(spreadsheetId).getSheetByName(sheetName);if(!sheet)throw apiError_(404,'Executive identity tab was not found: '+sheetName);var table=readConnectedTable_(sheet,AGENT_CONNECTION_ALIASES,['employeeId','name','email','doj']);var result=saveConnectionConfiguration_(context,'agent',spreadsheetId,sheetName,'Executive identity');return{spreadsheetId:result.spreadsheetId,sheetName:result.sheetName,rowCount:table.rows.length};}

function refreshAgentDataDump_(context){
  var config=configurationMap_();var platformSpreadsheetId=requiredProperty_('SPREADSHEET_ID');var spreadsheet=SpreadsheetApp.openById(platformSpreadsheetId);var target=spreadsheet.getSheetByName('agentDataDump');if(!target)throw apiError_(404,'Required app interface tab was not found: agentDataDump');var configuredName=String(config.agentSheetName||'').trim();var configuredSpreadsheetId=normalizeSpreadsheetId_(config.agentSpreadsheetId||platformSpreadsheetId);var source=null;var values=[];
  try{if(configuredName&&configuredName!=='agentDataDump'){var configuredSpreadsheet=SpreadsheetApp.openById(configuredSpreadsheetId);var configuredSheet=configuredSpreadsheet.getSheetByName(configuredName);if(!configuredSheet)throw apiError_(404,'Configured executive identity tab was not found: '+configuredName);source={name:configuredName};values=readAgentIdentitySheetValues_(configuredSheet);}else{source=findAgentIdentityDataSource_(spreadsheet);if(!source)return{refreshed:false,sourceSheet:'',reason:'NO_CONNECTED_SOURCE'};values=readAgentDataSourceValues_(source.dataSourceSheet);}}catch(error){if(target.getLastRow()>1){console.error('Connected executive refresh failed; retaining last successful mirror: '+error.message);return{refreshed:false,sourceSheet:source&&source.name||configuredName,rowCount:target.getLastRow()-1,reason:'STALE_FALLBACK',warning:error.message};}throw apiError_(503,'Connected Sheet refresh failed: '+error.message);}
  if(!values.length){if(target.getLastRow()>1)return{refreshed:false,sourceSheet:source.name,rowCount:target.getLastRow()-1,reason:'EMPTY_SOURCE_FALLBACK'};return{refreshed:false,sourceSheet:source.name,rowCount:0,reason:'CONNECTED_SOURCE_EMPTY'};}
  validateAgentDumpRows_(values.map(function(row){return{dataMonth:row[0],employeeId:row[1],name:row[2],email:row[3],doj:row[4],manager:row[5]};}));
  ensureAgentRefreshTrigger_();
  return withWriteLock_(function(){var previousRows=Math.max(0,target.getLastRow()-1);var previous=previousRows?target.getRange(2,1,previousRows,6).getDisplayValues():[];var cachedRecords=values.map(function(row){return{data_month:row[0],employee_id:row[1],executive_name:row[2],email:row[3],doj:row[4],manager:row[5]};});if(safeJson_(previous)===safeJson_(values)){repositoryCacheInvalidate_('agentDataDump');repositoryCacheWrite_('agentDataDump',cachedRecords);return{refreshed:false,sourceSheet:source.name,rowCount:values.length,reason:'UNCHANGED'};}if(previousRows)target.getRange(2,1,previousRows,6).clearContent();target.getRangeList(['A2:A'+(values.length+1),'E2:E'+(values.length+1)]).setNumberFormat('@');target.getRange(2,1,values.length,6).setValues(values);repositoryCacheInvalidate_('agentDataDump');repositoryCacheWrite_('agentDataDump',cachedRecords);audit_(context,'agentDataDump','Executive Connection','REFRESH','',{rowCount:previous.length},{rowCount:values.length,sourceSheet:source.name},'Scheduled refresh of app-readable executive identity snapshot',1);return{refreshed:true,sourceSheet:source.name,rowCount:values.length,reason:'UPDATED'};});
}

function findAgentIdentityDataSource_(spreadsheet){
  var ordered=[];var preferred=spreadsheet.getSheetByName('Connected Sheet 1');if(preferred)ordered.push(preferred);spreadsheet.getSheets().forEach(function(sheet){if(ordered.indexOf(sheet)<0)ordered.push(sheet);});
  for(var index=0;index<ordered.length;index++){try{var dataSourceSheet=ordered[index].asDataSourceSheet();if(dataSourceSheet)return{name:ordered[index].getName(),dataSourceSheet:dataSourceSheet};}catch(error){console.warn('Unable to inspect connected tab '+ordered[index].getName()+': '+error.message);}}
  return null;
}

function readAgentDataSourceValues_(dataSourceSheet){
  var columns=['data_month','employee_id','executive_name','email','doj','manager'];var valuesByColumn=columns.map(function(name){return dataSourceSheet.getSheetValues(name);});var rowCount=valuesByColumn.reduce(function(max,values){return Math.max(max,values.length);},0);var rows=[];
  for(var rowIndex=0;rowIndex<rowCount;rowIndex++){var row=valuesByColumn.map(function(values){return values[rowIndex]===undefined?'':values[rowIndex];});if(normalizedHeader_(row[1])==='employeeid'||!String(row[1]||'').trim())continue;rows.push([monthOnly_(row[0]),String(row[1]||'').trim(),String(row[2]||'').trim(),normalizeEmail_(row[3]),dateOnly_(row[4]),String(row[5]||'').trim()]);}
  return rows;
}

function readAgentIdentitySheetValues_(sheet){try{var dataSourceSheet=sheet.asDataSourceSheet();if(dataSourceSheet)return readAgentDataSourceValues_(dataSourceSheet);}catch(error){console.warn('Configured executive tab is not a Connected Sheet: '+error.message);}var table=readConnectedTable_(sheet,AGENT_CONNECTION_ALIASES,['employeeId','name','email','doj']);return table.rows.map(function(row){return[monthOnly_(row.dataMonth),String(row.employeeId||'').trim(),String(row.name||'').trim(),normalizeEmail_(row.email),dateOnly_(row.doj),String(row.manager||'').trim()];});}

function ensureAgentRefreshTrigger_(){var exists=ScriptApp.getProjectTriggers().some(function(trigger){return trigger.getHandlerFunction()==='dailyAgentDataRefreshJob';});if(!exists)ScriptApp.newTrigger('dailyAgentDataRefreshJob').timeBased().everyDays(1).atHour(2).create();}

function readAgentDump_(context,payload){
  payload=payload||{};var requestedMonth=String(payload.month||'').slice(0,7);var maximum=Math.max(1,Math.min(10000,Number(payload.limit)||1000));var snapshotRows=new SheetRepository_('agentDataDump').all();
  var normalized=snapshotRows.map(function(row){return{dataMonth:monthOnly_(row.data_month),employeeId:String(row.employee_id||'').trim(),name:String(row.executive_name||'').trim(),email:normalizeEmail_(row.email),doj:dateOnly_(row.doj),manager:String(row.manager||'').trim()};});
  var availableMonths={};normalized.forEach(function(row){if(row.dataMonth)availableMonths[row.dataMonth]=true;});if(normalized.length>maximum)normalized=normalized.slice(0,maximum);
  return{rows:normalized,sourceSheet:'agentDataDump',sourceSpreadsheetId:requiredProperty_('SPREADSHEET_ID'),availableMonths:Object.keys(availableMonths).sort().reverse(),requestedMonth:requestedMonth,sync:{refreshed:false,sourceSheet:'agentDataDump',rowCount:normalized.length,reason:'SCHEDULED_SNAPSHOT'}};
}

function previewAgentDump_(context,payload){requireRole_(context,['ADMIN']);var result=readAgentDump_(context,payload);validateAgentDumpRows_(result.rows);return{rows:result.rows,count:result.rows.length,sourceSheet:result.sourceSheet,sourceSpreadsheetId:result.sourceSpreadsheetId,availableMonths:result.availableMonths,requestedMonth:result.requestedMonth,sync:result.sync};}

function importAgentDump_(context,payload){
  requireRole_(context,['ADMIN']);payload=payload||{};var mappingMonth=String(payload.month||'');if(!/^\d{4}-\d{2}$/.test(mappingMonth))throw apiError_(400,'Mapping month must be YYYY-MM.');var source=readAgentDump_(context,{limit:payload.limit||10000,month:mappingMonth});var allInputs=source.rows;if(!allInputs.length)throw apiError_(400,'The scheduled agentDataDump snapshot has no active rows. Run the scheduled refresh job after the Connected Sheet finishes refreshing.');validateAgentDumpRows_(allInputs);
  var requested=(payload.employeeIds||[]).map(function(value){return String(value||'').trim().toUpperCase();}).filter(String);if(!requested.length)throw apiError_(400,'Select at least one executive to import.');var requestedLookup={};requested.forEach(function(value){requestedLookup[value]=true;});var inputs=allInputs.filter(function(input){return requestedLookup[input.employeeId.toUpperCase()];});if(inputs.length!==Object.keys(requestedLookup).length)throw apiError_(400,'One or more selected employee IDs are no longer present in '+source.sourceSheet+'. Fetch the connection again.');
  var details=payload.details||{};var managerOverride=String(details.manager||'').trim();var sourceName=String(details.source||'').trim();var suppliedTenurity=String(details.tenurity||'').trim();var tenurity=suppliedTenurity?normalizeTenurity_(suppliedTenurity):'';var suppliedStatus=String(details.status||'').trim().toUpperCase();var suppliedUpdatedAt=String(details.updatedAt||'').trim();var detailOverrides={};(payload.overrides||[]).forEach(function(item){var employeeId=String(item.employeeId||'').trim().toUpperCase();if(!employeeId)throw apiError_(400,'Connected agent override requires Employee ID.');var itemTenurity=String(item.tenurity||'').trim();detailOverrides[employeeId]={source:String(item.source||'').trim(),tenurity:itemTenurity?normalizeTenurity_(itemTenurity):'',selectedWeeks:Object.prototype.hasOwnProperty.call(item,'selectedWeeks')?parseSelectedWeeks_(item.selectedWeeks,mappingMonth):null};});if(suppliedStatus&&['ACTIVE','INACTIVE'].indexOf(suppliedStatus)<0)throw apiError_(400,'Status must be ACTIVE or INACTIVE.');if(!suppliedUpdatedAt||isNaN(new Date(suppliedUpdatedAt).getTime()))throw apiError_(400,'Updated At must be a valid date and time.');var missingManagers=inputs.filter(function(input){return !managerOverride&&!input.manager;});if(missingManagers.length)throw apiError_(400,'Manager is missing for: '+missingManagers.slice(0,10).map(function(input){return input.employeeId;}).join(', '));
  return withWriteLock_(function(){
    var repo=new SheetRepository_('executives');var rows=repo.all();var mappingRepo=new SheetRepository_('monthlyMappings');var mappings=mappingRepo.all();var byEmployee={};rows.forEach(function(row,index){byEmployee[String(row.employeeId).toUpperCase()]=index;});
    var missingTenurity=inputs.filter(function(input){var key=input.employeeId.toUpperCase();var index=byEmployee[key];return !(detailOverrides[key]&&detailOverrides[key].tenurity)&&!tenurity&&index===undefined;});if(missingTenurity.length)throw apiError_(400,'Tenurity is required only for new executives without a baseline: '+missingTenurity.slice(0,10).map(function(input){return input.employeeId;}).join(', '));
    var stamp=now_();var effectiveUpdatedAt=new Date(suppliedUpdatedAt).toISOString();var executiveIds=[];var importedRecords=[];
    inputs.forEach(function(input){var key=input.employeeId.toUpperCase();var index=Object.prototype.hasOwnProperty.call(byEmployee,key)?byEmployee[key]:-1;var existing=index>=0?rows[index]:null;var defaults=existing?mappingDefaultsForExecutive_(existing,mappings,mappingMonth):null;var itemOverride=detailOverrides[key]||{};var manager=managerOverride||input.manager;var effectiveSource=itemOverride.source||sourceName||String(defaults&&defaults.source||'').trim();var effectiveTenurity=itemOverride.tenurity||tenurity||String(defaults&&defaults.tenurity||'').trim();var effectiveStatus=suppliedStatus||String(defaults&&defaults.status||'ACTIVE').toUpperCase();if(!effectiveSource)throw apiError_(400,'Source is required for new executive '+input.employeeId+'.');if(!effectiveTenurity)throw apiError_(400,'Tenurity is required for new executive '+input.employeeId+'.');var record={id:existing?existing.id:id_(),employeeId:input.employeeId,name:input.name,email:input.email,doj:dateOnly_(input.doj),status:effectiveStatus,manager:manager,source:effectiveSource,tenurity:effectiveTenurity,active:effectiveStatus==='ACTIVE',createdAt:existing?existing.createdAt:stamp,updatedAt:effectiveUpdatedAt};if(index>=0)rows[index]=record;else{byEmployee[key]=rows.length;rows.push(record);}executiveIds.push(record.id);importedRecords.push(record);});
    var selectedWeeks=Object.prototype.hasOwnProperty.call(payload,'selectedWeeks')?parseSelectedWeeks_(payload.selectedWeeks,mappingMonth):monthWeekStarts_(mappingMonth);var alreadyMapped={};mappings.filter(function(row){return monthOnly_(row.month)===mappingMonth;}).forEach(function(row){alreadyMapped[row.executiveId]=true;});var mappingAdditions=importedRecords.filter(function(row){return !alreadyMapped[row.id];}).map(function(row){var itemOverride=detailOverrides[String(row.employeeId).toUpperCase()]||{};var rowWeeks=Array.isArray(itemOverride.selectedWeeks)?itemOverride.selectedWeeks:selectedWeeks;return{id:id_(),month:mappingMonth,executiveId:row.id,employeeId:row.employeeId,name:row.name,email:row.email,manager:row.manager,source:row.source,tenurity:row.tenurity,status:row.status,frozenAt:stamp,createdAt:stamp,createdBy:context.email,selectedWeeks:rowWeeks};});
    repo.replaceAll(rows);mappingRepo.insertMany(mappingAdditions);new SheetRepository_('sheetImports').insertMany([{id:id_(),type:'EXECUTIVE_CONNECTION',fileName:source.sourceSheet,status:'SUCCESS',rowCount:inputs.length,errorCount:0,createdAt:stamp,createdBy:context.email}]);audit_(context,'executives','Connections','BULK_UPSERT','',null,{rowCount:inputs.length,employeeIds:inputs.map(function(input){return input.employeeId;}),managerOverride:managerOverride,sourceChange:sourceName||'PRESERVE_OR_REQUIRE_NEW',tenurityChange:tenurity||'AUTO_FROM_BASELINE',statusChange:suppliedStatus||'PRESERVE_OR_ACTIVE_NEW',updatedAt:effectiveUpdatedAt,dataMonth:source.requestedMonth,sourceSheet:source.sourceSheet,sourceSpreadsheetId:source.sourceSpreadsheetId},'Connected executive identity import',1);audit_(context,'monthlyMappings','Mapping','CONNECTED_BATCH_CREATE','',null,{month:mappingMonth,rowCount:mappingAdditions.length,executiveIds:executiveIds,selectedWeeks:selectedWeeks},'Confirmed connected executive import and monthly mapping',1);return{imported:inputs.length,total:rows.length,executiveIds:executiveIds,mappingsCreated:mappingAdditions.length,sourceSheet:source.sourceSheet,sourceSpreadsheetId:source.sourceSpreadsheetId};
  });
}

function validateAgentDumpRows_(rows){var seen={};rows.forEach(function(row){['employeeId','name','email','doj'].forEach(function(field){if(!String(row[field]||'').trim())throw apiError_(400,'Connected executive '+field+' is required.');});if(!/^\S+@\S+\.\S+$/.test(row.email))throw apiError_(400,'Invalid executive email: '+row.email);if(isNaN(new Date(row.doj).getTime()))throw apiError_(400,'Invalid DOJ for '+row.employeeId);var key=row.employeeId.toUpperCase();if(seen[key])throw apiError_(409,'Duplicate Employee ID in the selected source month: '+row.employeeId);seen[key]=true;});}
