var AGENT_CONNECTION_ALIASES={datamonth:'dataMonth',month:'dataMonth',employeeid:'employeeId',executivename:'name',name:'name',agentname:'name',email:'email',workemail:'email',doj:'doj',dateofjoining:'doj',manager:'manager',manageremail:'manager',reportingmanager:'manager'};

function agentConnection_(){var excluded={};Object.keys(PLATFORM.SHEETS).forEach(function(name){excluded[name]=true;});delete excluded.agentDataDump;return resolveSheetConnection_({label:'executive identity',spreadsheetKey:'agentSpreadsheetId',sheetKey:'agentSheetName',aliases:AGENT_CONNECTION_ALIASES,required:['employeeId','name','email','doj'],candidates:['agentDataDump','Connected Sheet 1','bigQueryAgentDump'],exclude:excluded});}
function configureAgentSheet_(context,payload){requireRole_(context,['ADMIN']);var spreadsheetId=normalizeSpreadsheetId_(payload.spreadsheetId);var sheetName=String(payload.sheetName||'').trim();if(!spreadsheetId||!sheetName)throw apiError_(400,'Executive identity spreadsheet and tab name are required.');var sheet=SpreadsheetApp.openById(spreadsheetId).getSheetByName(sheetName);if(!sheet)throw apiError_(404,'Executive identity tab was not found: '+sheetName);var table=readConnectedTable_(sheet,AGENT_CONNECTION_ALIASES,['employeeId','name','email','doj']);var result=saveConnectionConfiguration_(context,'agent',spreadsheetId,sheetName,'Executive identity');return{spreadsheetId:result.spreadsheetId,sheetName:result.sheetName,rowCount:table.rows.length};}

function refreshAgentDataDump_(context){
  var config=configurationMap_();var spreadsheetId=normalizeSpreadsheetId_(config.agentSpreadsheetId||requiredProperty_('SPREADSHEET_ID'));var configuredName=String(config.agentSheetName||'').trim();
  if(configuredName&&configuredName!=='agentDataDump')return{refreshed:false,sourceSheet:configuredName,reason:'DIRECT_CONNECTION'};
  var spreadsheet=SpreadsheetApp.openById(spreadsheetId);var target=spreadsheet.getSheetByName('agentDataDump');if(!target)throw apiError_(404,'Required app interface tab was not found: agentDataDump');
  var source=findAgentIdentityDataSource_(spreadsheet);if(!source)return{refreshed:false,sourceSheet:'',reason:'NO_CONNECTED_SOURCE'};
  var values;try{values=readAgentDataSourceValues_(source.dataSourceSheet);}catch(error){if(target.getLastRow()>1){console.error('Connected executive refresh failed; retaining last successful mirror: '+error.message);return{refreshed:false,sourceSheet:source.name,rowCount:target.getLastRow()-1,reason:'STALE_FALLBACK',warning:error.message};}throw apiError_(503,'Connected Sheet refresh failed: '+error.message);}
  if(!values.length){if(target.getLastRow()>1)return{refreshed:false,sourceSheet:source.name,rowCount:target.getLastRow()-1,reason:'EMPTY_SOURCE_FALLBACK'};return{refreshed:false,sourceSheet:source.name,rowCount:0,reason:'CONNECTED_SOURCE_EMPTY'};}
  validateAgentDumpRows_(values.map(function(row){return{dataMonth:row[0],employeeId:row[1],name:row[2],email:row[3],doj:row[4],manager:row[5]};}));
  ensureAgentRefreshTrigger_();
  return withWriteLock_(function(){var previousRows=Math.max(0,target.getLastRow()-1);var previous=previousRows?target.getRange(2,1,previousRows,6).getDisplayValues():[];if(safeJson_(previous)===safeJson_(values))return{refreshed:false,sourceSheet:source.name,rowCount:values.length,reason:'UNCHANGED'};if(previousRows)target.getRange(2,1,previousRows,6).clearContent();target.getRange(2,1,values.length,6).setValues(values);audit_(context,'agentDataDump','Executive Connection','REFRESH','',{rowCount:previous.length},{rowCount:values.length,sourceSheet:source.name},'Refresh app-readable executive identity mirror',1);return{refreshed:true,sourceSheet:source.name,rowCount:values.length,reason:'UPDATED'};});
}

function findAgentIdentityDataSource_(spreadsheet){
  var ordered=[];var preferred=spreadsheet.getSheetByName('Connected Sheet 1');if(preferred)ordered.push(preferred);spreadsheet.getSheets().forEach(function(sheet){if(ordered.indexOf(sheet)<0)ordered.push(sheet);});
  for(var index=0;index<ordered.length;index++){try{var dataSourceSheet=ordered[index].asDataSourceSheet();if(dataSourceSheet)return{name:ordered[index].getName(),dataSourceSheet:dataSourceSheet};}catch(error){console.warn('Unable to inspect connected tab '+ordered[index].getName()+': '+error.message);}}
  return null;
}

function readAgentDataSourceValues_(dataSourceSheet){
  var columns=['data_month','employee_id','executive_name','email','doj','manager'];var valuesByColumn=columns.map(function(name){return dataSourceSheet.getSheetValues(name);});var rowCount=valuesByColumn.reduce(function(max,values){return Math.max(max,values.length);},0);var rows=[];
  for(var rowIndex=0;rowIndex<rowCount;rowIndex++){var row=valuesByColumn.map(function(values){return values[rowIndex]===undefined?'':values[rowIndex];});if(normalizedHeader_(row[1])==='employeeid'||!String(row[1]||'').trim())continue;rows.push([monthOnly_(row[0]),String(row[1]||'').trim(),String(row[2]||'').trim(),normalizeEmail_(row[3]),dateOnly_(row[4]),String(row[5]||'').trim()]);}
  return rows;
}

function ensureAgentRefreshTrigger_(){var exists=ScriptApp.getProjectTriggers().some(function(trigger){return trigger.getHandlerFunction()==='dailyAgentDataRefreshJob';});if(!exists)ScriptApp.newTrigger('dailyAgentDataRefreshJob').timeBased().everyDays(1).atHour(2).create();}

function readAgentDump_(context,payload){
  payload=payload||{};var sync=refreshAgentDataDump_(context);var connection=agentConnection_();var requestedMonth=String(payload.month||'').slice(0,7);var maximum=Math.max(1,Math.min(10000,Number(payload.limit)||1000));
  var normalized=connection.rows.map(function(row){return{dataMonth:monthOnly_(row.dataMonth),employeeId:String(row.employeeId||'').trim(),name:String(row.name||'').trim(),email:normalizeEmail_(row.email),doj:dateOnly_(row.doj),manager:String(row.manager||'').trim()};});
  var availableMonths={};normalized.forEach(function(row){if(row.dataMonth)availableMonths[row.dataMonth]=true;});if(normalized.length>maximum)normalized=normalized.slice(0,maximum);
  return{rows:normalized,sourceSheet:connection.sourceSheet,sourceSpreadsheetId:connection.spreadsheetId,availableMonths:Object.keys(availableMonths).sort().reverse(),requestedMonth:requestedMonth,sync:sync};
}

function previewAgentDump_(context,payload){requireRole_(context,['ADMIN']);var result=readAgentDump_(context,payload);validateAgentDumpRows_(result.rows);return{rows:result.rows,count:result.rows.length,sourceSheet:result.sourceSheet,sourceSpreadsheetId:result.sourceSpreadsheetId,availableMonths:result.availableMonths,requestedMonth:result.requestedMonth,sync:result.sync};}

function importAgentDump_(context,payload){
  requireRole_(context,['ADMIN']);payload=payload||{};var source=readAgentDump_(context,{limit:payload.limit||10000,month:payload.month});var allInputs=source.rows;if(!allInputs.length)throw apiError_(400,'The connected executive source has no active rows. Refresh the Connected Sheet query and retry.');validateAgentDumpRows_(allInputs);
  var requested=(payload.employeeIds||[]).map(function(value){return String(value||'').trim().toUpperCase();}).filter(String);if(!requested.length)throw apiError_(400,'Select at least one executive to import.');var requestedLookup={};requested.forEach(function(value){requestedLookup[value]=true;});var inputs=allInputs.filter(function(input){return requestedLookup[input.employeeId.toUpperCase()];});if(inputs.length!==Object.keys(requestedLookup).length)throw apiError_(400,'One or more selected employee IDs are no longer present in '+source.sourceSheet+'. Fetch the connection again.');
  var details=payload.details||{};var managerOverride=String(details.manager||'').trim();var sourceName=String(details.source||'').trim();var suppliedTenurity=String(details.tenurity||'').trim();var tenurity=suppliedTenurity?normalizeTenurity_(suppliedTenurity):'';var status=String(details.status||'ACTIVE').trim().toUpperCase();var suppliedUpdatedAt=String(details.updatedAt||'').trim();if(!sourceName)throw apiError_(400,'Source is required for the selected executives.');if(['ACTIVE','INACTIVE'].indexOf(status)<0)throw apiError_(400,'Status must be ACTIVE or INACTIVE.');if(!suppliedUpdatedAt||isNaN(new Date(suppliedUpdatedAt).getTime()))throw apiError_(400,'Updated At must be a valid date and time.');var missingManagers=inputs.filter(function(input){return !managerOverride&&!input.manager;});if(missingManagers.length)throw apiError_(400,'Manager is missing for: '+missingManagers.slice(0,10).map(function(input){return input.employeeId;}).join(', '));
  return withWriteLock_(function(){var repo=new SheetRepository_('executives');var rows=repo.all();var byEmployee={};rows.forEach(function(row,index){byEmployee[String(row.employeeId).toUpperCase()]=index;});var missingTenurity=inputs.filter(function(input){var index=byEmployee[input.employeeId.toUpperCase()];var existing=index===undefined?null:rows[index];return !tenurity&&(!existing||['M0','M1','M1+'].indexOf(String(existing.tenurity||'').trim().toUpperCase())<0);});if(missingTenurity.length)throw apiError_(400,'Tenurity is required for executives without a stored value: '+missingTenurity.slice(0,10).map(function(input){return input.employeeId;}).join(', '));var stamp=now_();var effectiveUpdatedAt=new Date(suppliedUpdatedAt).toISOString();var executiveIds=[];inputs.forEach(function(input){var key=input.employeeId.toUpperCase();var index=Object.prototype.hasOwnProperty.call(byEmployee,key)?byEmployee[key]:-1;var existing=index>=0?rows[index]:null;var manager=managerOverride||input.manager;var effectiveTenurity=tenurity||String(existing.tenurity).trim().toUpperCase();var record={id:existing?existing.id:id_(),employeeId:input.employeeId,name:input.name,email:input.email,doj:input.doj,status:status,manager:manager,source:sourceName,tenurity:effectiveTenurity,active:status==='ACTIVE',createdAt:existing?existing.createdAt:stamp,updatedAt:effectiveUpdatedAt};if(index>=0)rows[index]=record;else{byEmployee[key]=rows.length;rows.push(record);}executiveIds.push(record.id);});repo.replaceAll(rows);new SheetRepository_('sheetImports').insertMany([{id:id_(),type:'EXECUTIVE_CONNECTION',fileName:source.sourceSheet,status:'SUCCESS',rowCount:inputs.length,errorCount:0,createdAt:stamp,createdBy:context.email}]);audit_(context,'executives','Connections','BULK_UPSERT','',null,{rowCount:inputs.length,employeeIds:inputs.map(function(input){return input.employeeId;}),managerOverride:managerOverride,source:sourceName,tenurityChange:tenurity||'UNCHANGED',status:status,updatedAt:effectiveUpdatedAt,dataMonth:source.requestedMonth,sourceSheet:source.sourceSheet,sourceSpreadsheetId:source.sourceSpreadsheetId},'Connected executive identity import',1);return{imported:inputs.length,total:rows.length,executiveIds:executiveIds,sourceSheet:source.sourceSheet,sourceSpreadsheetId:source.sourceSpreadsheetId};});
}

function validateAgentDumpRows_(rows){var seen={};rows.forEach(function(row){['employeeId','name','email','doj'].forEach(function(field){if(!String(row[field]||'').trim())throw apiError_(400,'Connected executive '+field+' is required.');});if(!/^\S+@\S+\.\S+$/.test(row.email))throw apiError_(400,'Invalid executive email: '+row.email);if(isNaN(new Date(row.doj).getTime()))throw apiError_(400,'Invalid DOJ for '+row.employeeId);var key=row.employeeId.toUpperCase();if(seen[key])throw apiError_(409,'Duplicate Employee ID in the selected source month: '+row.employeeId);seen[key]=true;});}
