function monday_(date){var value=new Date(date||new Date());var day=value.getUTCDay();value.setUTCDate(value.getUTCDate()-(day===0?6:day-1));return value.toISOString().slice(0,10);}
function weekBusinessMonth_(weekStart){var thursday=new Date(dateOnly_(weekStart)+'T00:00:00Z');thursday.setUTCDate(thursday.getUTCDate()+3);return thursday.toISOString().slice(0,7);}

function targetForDate_(targets,source,tenurity,date){return targets.filter(function(item){return String(item.source).toLowerCase()===String(source).toLowerCase()&&item.tenurity===tenurity&&String(item.effectiveFrom)<=date&&(!item.effectiveTo||String(item.effectiveTo)>=date);}).sort(function(a,b){return String(b.effectiveFrom).localeCompare(String(a.effectiveFrom));})[0]||null;}

function generatePlanningSnapshot_(context,payload){var kind=String(payload.kind||'');if(['weekly','monthly'].indexOf(kind)<0)throw apiError_(400,'Planning kind must be weekly or monthly.');return withWriteLock_(function(){var stamp=now_();if(kind==='weekly'){var period=monday_(new Date());var month=weekBusinessMonth_(period);var snapshots=new SheetRepository_('weeklySnapshots');if(snapshots.find(function(row){return dateOnly_(row.weekStart)===period;}).length)throw apiError_(409,'The current weekly snapshot is already frozen.');var monthly=listMonthlyMappings_({month:month}).filter(function(row){return String(row.status).toUpperCase()==='ACTIVE'&&parseSelectedWeeks_(row.selectedWeeks,month).indexOf(period)>=0;});var mappings=monthly.map(function(row){return{id:id_(),weekStart:period,executiveId:row.executiveId,employeeId:row.employeeId,name:row.name,manager:row.manager,source:row.source,tenurity:normalizeTenurity_(row.tenurity),status:row.status,frozenAt:stamp,createdAt:stamp};});var targetVersions=listTargets_();var weeklyTargets=mappings.map(function(mapping){var target=targetForDate_(targetVersions,mapping.source,mapping.tenurity,period);return{id:id_(),weekStart:period,executiveId:mapping.executiveId,source:mapping.source,tenurity:mapping.tenurity,targetVersion:target?target.version:'',revenue:Number(target&&target.revenue)||0,login:Number(target&&target.login)||0,demo:Number(target&&target.demo)||0,license:Number(target&&target.license)||0,proPlatform:Number(target&&target.proPlatform)||0,arpl:Number(target&&target.arpl)||0,createdAt:stamp};});new SheetRepository_('weeklyMappings').insertMany(mappings);new SheetRepository_('weeklyTargets').insertMany(weeklyTargets);snapshots.insertMany([{id:id_(),weekStart:period,status:'FROZEN',rowCount:mappings.length,createdAt:stamp,createdBy:context.email}]);audit_(context,'weeklySnapshots','Planning','CREATE',period,null,{businessMonth:month,rowCount:mappings.length,targetRows:weeklyTargets.length},'Immutable weekly mapping and target snapshot using Thursday business month',1);return{period:period,businessMonth:month,executives:mappings.length,targets:weeklyTargets.length};}var currentMonth=monthOnly_(now_().slice(0,7));var monthlySnapshots=new SheetRepository_('monthlySnapshots');if(monthlySnapshots.find(function(row){return monthOnly_(row.month)===currentMonth;}).length)throw apiError_(409,'The current monthly snapshot is already frozen.');var mapped=listMonthlyMappings_({month:currentMonth});monthlySnapshots.insertMany([{id:id_(),month:currentMonth,status:'FROZEN',rowCount:mapped.length,createdAt:stamp,createdBy:context.email}]);audit_(context,'monthlySnapshots','Planning','CREATE',currentMonth,null,{rowCount:mapped.length},'Immutable monthly snapshot',1);return{period:currentMonth,executives:mapped.length};});}

function weeklyIncentiveRepository_(){var spreadsheet=SpreadsheetApp.openById(requiredProperty_('SPREADSHEET_ID'));if(!spreadsheet.getSheetByName('weeklyIncentives')){var lock=LockService.getScriptLock();lock.waitLock(30000);try{if(!spreadsheet.getSheetByName('weeklyIncentives'))ensureSheet_(spreadsheet,'weeklyIncentives',PLATFORM.SHEETS.weeklyIncentives);}finally{lock.releaseLock();}}return new SheetRepository_('weeklyIncentives');}
function monthWeekStarts_(month){if(!/^\d{4}-\d{2}$/.test(month))throw apiError_(400,'Month must be YYYY-MM.');var date=new Date(month+'-01T00:00:00Z');var day=date.getUTCDay();date.setUTCDate(date.getUTCDate()-(day===0?6:day-1));var result=[];for(var index=0;index<6;index++){var weekStart=date.toISOString().slice(0,10);if(weekBusinessMonth_(weekStart)===month)result.push(weekStart);date.setUTCDate(date.getUTCDate()+7);}return result;}
var LOCAL_TEST_INCENTIVE_RULE_VERSION_='WEEKLY_TEAM_V1';
var LEGACY_AGENT_INCENTIVE_SLABS_=[{threshold:0.8,amount:2000},{threshold:0.9,amount:2700},{threshold:1,amount:3500},{threshold:1.1,amount:4000},{threshold:1.3,amount:4500},{threshold:1.5,amount:5000},{threshold:2,amount:6500}];
var AGENT_INCENTIVE_SLABS_=[{threshold:0.7,amount:1500},{threshold:0.8,amount:2000},{threshold:0.9,amount:2700},{threshold:1,amount:3500},{threshold:1.1,amount:4000}];
var TEAM_LEAD_INCENTIVE_SLABS_=[{threshold:0.8,amount:250},{threshold:0.9,amount:300},{threshold:1,amount:350}];
var TEAM_LEAD_BASE_SLABS_=[{threshold:0.7,amount:1500},{threshold:0.8,amount:2000},{threshold:0.9,amount:2700},{threshold:1,amount:3500}];
var TEAM_LEAD_BONUS_SLABS_=[{threshold:1,amount:0},{threshold:2,amount:0},{threshold:3,amount:5000},{threshold:4,amount:7500}];
var LEGACY_FOUR_WEEK_BONUS_SLABS_=[{threshold:1,amount:0},{threshold:2,amount:0},{threshold:3,amount:3000},{threshold:4,amount:6000}];
var FOUR_WEEK_BONUS_SLABS_=[{threshold:1,amount:0},{threshold:2,amount:0},{threshold:3,amount:5000},{threshold:4,amount:7500}];
var FIVE_WEEK_BONUS_SLABS_=[{threshold:1,amount:0},{threshold:2,amount:0},{threshold:3,amount:3000},{threshold:4,amount:6000},{threshold:5,amount:9000}];
function floorSlabAmount_(achievement,slabs){var value=Number(achievement)||0;var earned=0;(slabs||[]).forEach(function(slab){if(value>=Number(slab.threshold))earned=Number(slab.amount)||0;});return earned;}
function incentiveAmountForAchievement_(achievement,slabs){return floorSlabAmount_(achievement,slabs||AGENT_INCENTIVE_SLABS_);}
function teamIncentiveForAchievement_(achievement,slabs){return floorSlabAmount_(achievement,slabs||TEAM_LEAD_INCENTIVE_SLABS_);}
function achievementBonusForWeeks_(qualifiedWeeks,monthWeeks,slabs){var count=Math.max(0,Math.floor(Number(qualifiedWeeks)||0));var fallback=Number(monthWeeks)===4?FOUR_WEEK_BONUS_SLABS_:FIVE_WEEK_BONUS_SLABS_;return floorSlabAmount_(count,slabs||fallback);}
function incentiveAmounts_(target,revenue,m2Target,agentSlabs,teamLeadSlabs){var weeklyTarget=Number(target)||0;var achieved=Number(revenue)||0;var achievement=weeklyTarget>0?achieved/weeklyTarget:0;var incentiveAmount=incentiveAmountForAchievement_(achievement,agentSlabs);return{achievement:achievement,bonus:0,incentiveAmount:incentiveAmount,incentive:incentiveAmount,teamIncentive:teamIncentiveForAchievement_(achievement,teamLeadSlabs)};}

function nullableNumber_(value){return value===''||value===null||value===undefined?null:Number(value);}
function teamLeadSummaryRows_(agentRows,weeks,calculationVersion,incentiveRules,month){var groups={};agentRows.forEach(function(row){var manager=String(row.teamLead||row.manager||'').trim();if(!manager)return;var key=manager.toLowerCase();if(!groups[key])groups[key]={manager:manager,agents:[]};groups[key].agents.push(row);});return Object.keys(groups).map(function(key){var group=groups[key];var monthTarget=0;var monthRevenue=0;var monthM2Target=0;var teamIncentive=0;var baseIncentive=0;var qualifiedWeeks=0;var weeklyValues={};weeks.forEach(function(week){var values=group.agents.map(function(agent){return agent.weeks[week]||{};}).filter(function(item){return item.target!==null&&item.target!==undefined&&item.target!==''&&item.eligibleRevenue!==null&&item.eligibleRevenue!==undefined&&item.eligibleRevenue!=='';});if(!values.length){weeklyValues[week]={target:null,m2Target:null,eligibleRevenue:null,achievement:null,incentiveAmount:null,bonus:null,incentive:null,teamIncentive:null};return;}var target=values.reduce(function(sum,item){return sum+(Number(item.target)||0);},0);var revenue=values.reduce(function(sum,item){return sum+(Number(item.eligibleRevenue)||0);},0);var m2Target=values.reduce(function(sum,item){return sum+(Number(item.m2Target)||0);},0);var payout=values.reduce(function(sum,item){return sum+(Number(item.teamIncentive)||0);},0);var achievement=target?revenue/target:0;var baseRule=configuredRuleSetForDate_(incentiveRules||[],'TL_INCENTIVE',week);var weeklyBase=floorSlabAmount_(achievement,baseRule.slabs);monthTarget+=target;monthRevenue+=revenue;monthM2Target=Math.max(monthM2Target,m2Target);teamIncentive+=payout;baseIncentive+=weeklyBase;if(target>0&&achievement>=0.8)qualifiedWeeks++;weeklyValues[week]={target:target,m2Target:m2Target,eligibleRevenue:revenue,achievement:achievement,incentiveAmount:weeklyBase,bonus:0,incentive:weeklyBase,teamIncentive:payout};});var bonusRule=configuredRuleSetForDate_(incentiveRules||[],'TL_BONUS',(month||'9999-12')+'-01');var bonus=achievementBonusForWeeks_(qualifiedWeeks,weeks.length,bonusRule.slabs);return{id:'team-lead:'+key,rowType:'TEAM_LEAD',executiveId:'',executiveName:group.manager,employeeId:'',email:'',manager:group.manager,teamLead:group.manager,source:'',tenurity:'',weeks:weeklyValues,monthTotal:{m2Target:monthM2Target,target:monthTarget,revenue:monthRevenue,achievement:monthTarget?monthRevenue/monthTarget:0,qualifiedWeeks:qualifiedWeeks,bonus:bonus,incentive:baseIncentive,teamIncentive:teamIncentive,totalPayout:baseIncentive+teamIncentive+bonus},calculationVersion:calculationVersion};}).sort(function(left,right){return left.executiveName.localeCompare(right.executiveName);});}
function listIncentives_(payload){
  var month=monthOnly_(payload.month||now_().slice(0,7));
  var monthly=new SheetRepository_('incentives').find(function(row){return monthOnly_(row.month)===month;});
  var latestVersion=monthly.reduce(function(max,row){return Math.max(max,Number(row.calculationVersion)||0);},0);
  var monthlyLatest=monthly.filter(function(row){return Number(row.calculationVersion)===latestVersion;});
  var weekly=weeklyIncentiveRepository_().find(function(row){return monthOnly_(row.month)===month&&Number(row.calculationVersion)===latestVersion;});
  var mappings=listMonthlyMappings_({month:month});var mappingByExecutive={};var mappingByEmployee={};var mappingByEmail={};var mappingByName={};mappings.forEach(function(row){mappingByExecutive[String(row.executiveId)]=row;if(row.employeeId)mappingByEmployee[String(row.employeeId).toUpperCase()]=row;if(row.email)mappingByEmail[String(row.email).toLowerCase()]=row;if(row.name)mappingByName[String(row.name).trim().toLowerCase()]=row;});
  var weeks=monthWeekStarts_(month);var byExecutive={};
  weekly.forEach(function(row){if(!byExecutive[row.executiveId])byExecutive[row.executiveId]={};byExecutive[row.executiveId][dateOnly_(row.weekStart)]={target:nullableNumber_(row.target),m2Target:nullableNumber_(row.m2Target),eligibleRevenue:nullableNumber_(row.eligibleRevenue),achievement:nullableNumber_(row.achievement),incentiveAmount:nullableNumber_(row.incentiveAmount),bonus:nullableNumber_(row.bonus),incentive:nullableNumber_(row.incentive),teamIncentive:nullableNumber_(row.teamIncentive),source:String(row.source||''),tenurity:String(row.tenurity||'')};});
  var incentiveRules=new SheetRepository_('bonusRules').all();var bonusRule=configuredRuleSetForDate_(incentiveRules,weeks.length===4?'BONUS_4_WEEK':'BONUS_5_WEEK',month+'-01');var rows=monthlyLatest.map(function(row){var mapping=mappingByExecutive[String(row.executiveId)]||mappingByEmployee[String(row.employeeId||'').toUpperCase()]||mappingByEmail[String(row.email||'').toLowerCase()]||mappingByName[String(row.executiveName||'').trim().toLowerCase()]||{};var executiveWeeks=byExecutive[row.executiveId]||{};var weekValues=weeks.map(function(week){return executiveWeeks[week]||{};});var calculatedQualifiedWeeks=weekValues.filter(function(item){return Number(item.target)>0&&Number(item.achievement)>=0.8;}).length;var qualifiedWeeks=row.qualifiedWeeks===''||row.qualifiedWeeks===null||row.qualifiedWeeks===undefined?calculatedQualifiedWeeks:Number(row.qualifiedWeeks);var achievementBonus=Number(row.bonus)||achievementBonusForWeeks_(qualifiedWeeks,weeks.length,bonusRule.slabs);var teamIncentive=Number(row.teamIncentive)||weekValues.reduce(function(sum,item){return sum+(Number(item.teamIncentive)||0);},0);var weeklyAgentIncentive=weekValues.reduce(function(sum,item){return sum+(Number(item.incentive)||0);},0);var hasWeeklyValues=weekValues.some(function(item){return item.incentive!==null&&item.incentive!==undefined&&item.incentive!=='';});var agentIncentive=hasWeeklyValues?weeklyAgentIncentive:Number(row.incentive)||0;var weeklySource=(weekValues.find(function(item){return item.source;})||{}).source||'';var manager=mapping.manager||row.manager||'';return{id:row.id,rowType:'AGENT',executiveId:row.executiveId,executiveName:mapping.name||row.executiveName,employeeId:mapping.employeeId||row.employeeId||'',email:mapping.email||row.email||'',manager:manager,teamLead:manager,source:mapping.source||weeklySource||row.source||'',tenurity:mapping.tenurity||row.tenurity||'',weeks:executiveWeeks,monthTotal:{m2Target:Number(row.m2Target)||weekValues.reduce(function(max,item){return Math.max(max,Number(item.m2Target)||0);},0),target:Number(row.target)||0,revenue:Number(row.eligibleRevenue)||0,achievement:Number(row.achievement)||0,qualifiedWeeks:qualifiedWeeks,bonus:achievementBonus,incentive:agentIncentive,teamIncentive:teamIncentive,totalPayout:agentIncentive+achievementBonus},calculationVersion:Number(row.calculationVersion)||0};});
  return{month:month,weeks:weeks,rows:rows,teamLeadRows:teamLeadSummaryRows_(rows,weeks,latestVersion,incentiveRules,month),calculationVersion:latestVersion,ruleVersion:LOCAL_TEST_INCENTIVE_RULE_VERSION_};
}

function calculateIncentives_(context,payload){
  var month=monthOnly_(payload.month||now_().slice(0,7));var weekStarts=monthWeekStarts_(month);weeklyIncentiveRepository_();
  return withWriteLock_(function(){
    var mappings=listMonthlyMappings_({month:month});
    var weeklyMappings=new SheetRepository_('weeklyMappings').find(function(row){return weekStarts.indexOf(dateOnly_(row.weekStart))>=0;});
    var targets=listTargets_();
    var frozenTargets=new SheetRepository_('weeklyTargets').find(function(row){return weekStarts.indexOf(dateOnly_(row.weekStart))>=0;});
    var performance=new SheetRepository_('performance').find(function(row){return String(row.periodType).toUpperCase()==='WEEK'&&weekStarts.indexOf(dateOnly_(row.period))>=0;});
    var incentiveRules=new SheetRepository_('bonusRules').all();var ruleSetsByWeek={};weekStarts.forEach(function(weekStart){ruleSetsByWeek[weekStart]={agent:configuredRuleSetForDate_(incentiveRules,'AGENT',weekStart),teamLead:configuredRuleSetForDate_(incentiveRules,'TEAM_LEAD',weekStart)};});var bonusRule=configuredRuleSetForDate_(incentiveRules,weekStarts.length===4?'BONUS_4_WEEK':'BONUS_5_WEEK',month+'-01');
    var oldMonthly=new SheetRepository_('incentives').find(function(row){return monthOnly_(row.month)===month;});
    var version=oldMonthly.reduce(function(max,row){return Math.max(max,Number(row.calculationVersion)||0);},0)+1;var stamp=now_();var weeklyRows=[];
    var monthlyRows=mappings.map(function(monthlyMapping){
      var totals={m2Target:0,target:0,revenue:0,qualifiedWeeks:0,incentive:0,teamIncentive:0,qualificationFlags:[]};var selected=parseSelectedWeeks_(monthlyMapping.selectedWeeks,month);
      weekStarts.forEach(function(weekStart){
        if(selected.indexOf(weekStart)<0){totals.qualificationFlags.push(false);weeklyRows.push({id:id_(),month:month,weekStart:weekStart,executiveId:monthlyMapping.executiveId,executiveName:monthlyMapping.name,manager:monthlyMapping.manager,target:'',eligibleRevenue:'',achievement:'',bonus:'',incentive:'',calculationVersion:version,createdAt:stamp,createdBy:context.email,m2Target:'',incentiveAmount:'',teamIncentive:'',source:monthlyMapping.source,tenurity:monthlyMapping.tenurity,employeeId:monthlyMapping.employeeId,email:monthlyMapping.email});return;}
        var mapping=weeklyMappings.find(function(item){return item.executiveId===monthlyMapping.executiveId&&dateOnly_(item.weekStart)===weekStart;})||monthlyMapping;
        var frozenTarget=frozenTargets.find(function(item){return item.executiveId===monthlyMapping.executiveId&&dateOnly_(item.weekStart)===weekStart;});
        var source=String((frozenTarget&&frozenTarget.source)||monthlyMapping.source||mapping.source||'');var tenurity=String((frozenTarget&&frozenTarget.tenurity)||mapping.tenurity||monthlyMapping.tenurity||'');
        var versionTarget=frozenTarget?null:targetForDate_(targets,source,tenurity,weekStart);
        var targetRevenue=Number(frozenTarget?frozenTarget.revenue:versionTarget&&versionTarget.revenue)||0;
        var m2VersionTarget=targetForDate_(targets,source,'M1+',weekStart);var m2Target=Number(m2VersionTarget&&m2VersionTarget.revenue)||0;if(!m2Target&&tenurity.toUpperCase()==='M1+')m2Target=targetRevenue;
        var actual=performance.find(function(item){return item.executiveId===monthlyMapping.executiveId&&dateOnly_(item.period)===weekStart;})||{};
        var revenue=Number(actual.revenue||0)+Number(actual.manualRevenue||0);var weekRules=ruleSetsByWeek[weekStart];var amounts=incentiveAmounts_(targetRevenue,revenue,m2Target,weekRules.agent.slabs,weekRules.teamLead.slabs);
        weeklyRows.push({id:id_(),month:month,weekStart:weekStart,executiveId:monthlyMapping.executiveId,executiveName:monthlyMapping.name,manager:monthlyMapping.manager,target:targetRevenue,eligibleRevenue:revenue,achievement:amounts.achievement,bonus:0,incentive:amounts.incentive,calculationVersion:version,createdAt:stamp,createdBy:context.email,m2Target:m2Target,incentiveAmount:amounts.incentiveAmount,teamIncentive:amounts.teamIncentive,source:source,tenurity:tenurity,employeeId:monthlyMapping.employeeId,email:monthlyMapping.email});
        totals.m2Target=Math.max(totals.m2Target,m2Target);totals.target+=targetRevenue;totals.revenue+=revenue;totals.incentive+=amounts.incentive;totals.teamIncentive+=amounts.teamIncentive;totals.qualificationFlags.push(targetRevenue>0&&amounts.achievement>=0.8);
      });
      totals.qualifiedWeeks=totals.qualificationFlags.filter(function(value){return value;}).length;var achievementBonus=achievementBonusForWeeks_(totals.qualifiedWeeks,weekStarts.length,bonusRule.slabs);
      return{id:id_(),month:month,executiveId:monthlyMapping.executiveId,executiveName:monthlyMapping.name,manager:monthlyMapping.manager,target:totals.target,eligibleRevenue:totals.revenue,achievement:totals.target?totals.revenue/totals.target:0,bonus:achievementBonus,incentive:totals.incentive,calculationVersion:version,createdAt:stamp,createdBy:context.email,m2Target:totals.m2Target,qualifiedWeeks:totals.qualifiedWeeks,teamIncentive:totals.teamIncentive,source:monthlyMapping.source,tenurity:monthlyMapping.tenurity,employeeId:monthlyMapping.employeeId,email:monthlyMapping.email};
    });
    var appliedRuleVersions={};Object.keys(ruleSetsByWeek).forEach(function(weekStart){appliedRuleVersions[weekStart]={agent:ruleSetsByWeek[weekStart].agent.version,teamLead:ruleSetsByWeek[weekStart].teamLead.version};});appliedRuleVersions.monthlyBonus={level:bonusRule.level,version:bonusRule.version};weeklyIncentiveRepository_().insertMany(weeklyRows);new SheetRepository_('incentives').insertMany(monthlyRows);audit_(context,'incentives','Incentive','CALCULATE',month,{previousRows:oldMonthly.length},{monthlyRows:monthlyRows.length,weeklyRows:weeklyRows.length,weeks:weekStarts,ruleVersions:appliedRuleVersions},'Scaled weekly agent slab award, configured monthly bonus, and team incentive calculation',version);return{month:month,calculationVersion:version,weeks:weekStarts,rows:monthlyRows,ruleVersion:JSON.stringify(appliedRuleVersions)};
  });
}

function rebuildIncentivesWithContext_(context,months){requireRole_(context,['ADMIN']);var periods=(months||[]).map(function(month){return monthOnly_(month);});if(!periods.length)throw apiError_(400,'Provide at least one calculation month.');var cleared=withWriteLock_(function(){var spreadsheet=SpreadsheetApp.openById(requiredProperty_('SPREADSHEET_ID'));var sheet=spreadsheet.getSheetByName('weeklyIncentives');if(!sheet)throw apiError_(404,'weeklyIncentives sheet was not found.');var rowCount=Math.max(0,sheet.getLastRow()-1);if(sheet.getMaxRows()>1)sheet.getRange(2,1,sheet.getMaxRows()-1,sheet.getMaxColumns()).clearContent();repositoryCacheInvalidate_('weeklyIncentives');audit_(context,'weeklyIncentives','Incentive','CLEAR_DATA','',null,{clearedRows:rowCount,months:periods},'Authorized rebuild using effective floor-slab and bonus rules',1);return rowCount;});var results=periods.map(function(month){return calculateIncentives_(context,{month:month});});return{clearedRows:cleared,months:periods,results:results.map(function(result){return{month:result.month,calculationVersion:result.calculationVersion,rowCount:result.rows.length};})};}
function rebuildIncentivesForMonths(months){var email=normalizeEmail_(Session.getEffectiveUser().getEmail());var user=new SheetRepository_('users').all().find(function(row){return normalizeEmail_(row.email)===email&&String(row.status).toUpperCase()==='ACTIVE';});return rebuildIncentivesWithContext_({email:email,role:user?String(user.role).toUpperCase():'',correlationId:id_()},months);}

function incentiveExportTable_(report){var blank=function(value){return value===null||value===undefined?'':value;};var headers=['Level','Team','Team Lead','EMP ID','Agent Name','Agent Email','Source M1+ Target','Monthly Target'];report.weeks.forEach(function(week,index){['Target','Achieved','Achievement %','Slab Incentive','TL Contribution'].forEach(function(metric){headers.push('Week '+(index+1)+' '+metric+' ('+week+')');});});headers=headers.concat(['Monthly Achieved','Monthly Achievement %','80%+ Weeks','Achievement Bonus','Slab Incentive','TL Milestone Contribution','Total Payout','Version']);var allRows=report.rows.concat(report.teamLeadRows||[]).sort(function(left,right){var leftKey=String(left.teamLead||left.manager||'').toLowerCase()+'|'+String(left.source||'').toLowerCase()+'|'+(left.rowType==='TEAM_LEAD'?'1':'0')+'|'+String(left.email||left.executiveName||'').toLowerCase();var rightKey=String(right.teamLead||right.manager||'').toLowerCase()+'|'+String(right.source||'').toLowerCase()+'|'+(right.rowType==='TEAM_LEAD'?'1':'0')+'|'+String(right.email||right.executiveName||'').toLowerCase();return leftKey.localeCompare(rightKey);});var rows=allRows.map(function(row){var isTeamLead=row.rowType==='TEAM_LEAD';var values=[isTeamLead?'Team lead':'Agent',row.source,row.teamLead||row.manager,row.employeeId,row.executiveName,isTeamLead?'':row.email,row.monthTotal.m2Target,row.monthTotal.target];report.weeks.forEach(function(week){var item=row.weeks[week]||{};values.push(blank(item.target),blank(item.eligibleRevenue),blank(item.achievement),blank(item.incentive),blank(item.teamIncentive));});return values.concat([row.monthTotal.revenue,row.monthTotal.achievement,row.monthTotal.qualifiedWeeks,row.monthTotal.bonus,row.monthTotal.incentive,row.monthTotal.teamIncentive,row.monthTotal.totalPayout,row.calculationVersion]);});return{headers:headers,rows:rows};}
function exportIncentivesToGoogleSheet_(context,payload){var report=listIncentives_(payload||{});if(!report.rows.length)throw apiError_(404,'Calculate incentives before exporting this month.');var table=incentiveExportTable_(report);var title='IB Incentives '+report.month+' v'+report.calculationVersion;var spreadsheet=SpreadsheetApp.create(title);var sheet=spreadsheet.getSheets()[0];sheet.setName('Incentives '+report.month);sheet.getRange(1,1,table.rows.length+1,table.headers.length).setValues([table.headers].concat(table.rows));sheet.setFrozenRows(1);sheet.getRange(1,1,1,table.headers.length).setFontWeight('bold').setBackground('#dbeafe').setWrap(true);sheet.autoResizeColumns(1,table.headers.length);sheet.getRange(2,3,table.rows.length,Math.max(1,table.headers.length-2)).setNumberFormat('#,##0.00');spreadsheet.addViewer(context.email);audit_(context,'incentives','Incentive','EXPORT',report.month,null,{spreadsheetId:spreadsheet.getId(),rowCount:table.rows.length},'Export incentive report to Google Sheet',report.calculationVersion);return{id:spreadsheet.getId(),url:spreadsheet.getUrl(),title:title,rowCount:table.rows.length};}

function dashboard_(payload){var month=monthOnly_(payload.month||now_().slice(0,7));var report=listIncentives_({month:month});var values=report.rows.map(function(row){return row.monthTotal;});var target=values.reduce(function(sum,row){return sum+Number(row.target||0);},0);var revenue=values.reduce(function(sum,row){return sum+Number(row.revenue||0);},0);var incentive=values.reduce(function(sum,row){return sum+Number(row.incentive||0);},0);return{activeExecutives:new SheetRepository_('executives').find(function(row){return row.active===true||String(row.active).toLowerCase()==='true';}).length,month:month,target:target,revenue:revenue,incentive:incentive,trend:[{month:month,target:target,revenue:revenue,incentive:incentive}]};}
