var REVENUE_CONNECTION_ALIASES={employeeid:'employeeId',periodtype:'periodType',period:'period',revenue:'revenue',login:'login',demo:'demo',license:'license',proplatform:'proPlatform',manualrevenue:'manualRevenue'};

function configureRevenueSheet_(context,payload){requireRole_(context,['ADMIN']);var spreadsheetId=normalizeSpreadsheetId_(payload.spreadsheetId);var sheetName=String(payload.sheetName||'').trim();if(!spreadsheetId||!sheetName)throw apiError_(400,'Revenue spreadsheet ID and sheet name are required.');var spreadsheet=SpreadsheetApp.openById(spreadsheetId);var sheet=spreadsheet.getSheetByName(sheetName);if(!sheet)throw apiError_(404,'Revenue sheet tab was not found.');readConnectedTable_(sheet,REVENUE_CONNECTION_ALIASES,['employeeId','periodType','period','revenue']);return saveConnectionConfiguration_(context,'revenue',spreadsheetId,sheetName,'Revenue');}

function revenueConnection_(){var excluded={};Object.keys(PLATFORM.SHEETS).forEach(function(name){excluded[name]=true;});return resolveSheetConnection_({label:'revenue',spreadsheetKey:'revenueSpreadsheetId',sheetKey:'revenueSheetName',aliases:REVENUE_CONNECTION_ALIASES,required:['employeeId','periodType','period','revenue'],candidates:['revenueDataDump','Revenue','revenueDump'],exclude:excluded});}

function readRevenueSource_(){var connection=revenueConnection_();var rows=connection.rows.map(function(input){var record={sourceRow:input.sourceRow,employeeId:String(input.employeeId||'').trim(),periodType:String(input.periodType||'MONTH').toUpperCase(),period:dateOnly_(input.period)};if(record.periodType==='WEEKLY')record.periodType='WEEK';if(record.periodType==='MONTHLY')record.periodType='MONTH';if(['WEEK','MONTH'].indexOf(record.periodType)<0)throw apiError_(400,'Period Type must be WEEK or MONTH at revenue source row '+record.sourceRow);if(record.periodType==='WEEK'&&!/^\d{4}-\d{2}-\d{2}$/.test(record.period))throw apiError_(400,'Weekly Period must be a Monday in YYYY-MM-DD format at revenue source row '+record.sourceRow);if(record.periodType==='WEEK'&&new Date(record.period+'T00:00:00Z').getUTCDay()!==1)throw apiError_(400,'Weekly Period must be a Monday at revenue source row '+record.sourceRow);['revenue','login','demo','license','proPlatform','manualRevenue'].forEach(function(field){record[field]=Number(input[field]||0);if(!isFinite(record[field])||record[field]<0)throw apiError_(400,'Invalid '+field+' at revenue source row '+record.sourceRow);});return record;});return{rows:rows,sourceSheet:connection.sourceSheet,sourceSpreadsheetId:connection.spreadsheetId};}

function previewRevenueSheet_(context){requireRole_(context,['ADMIN']);var source=readRevenueSource_();return{rows:source.rows.slice(0,200),count:source.rows.length,previewLimited:source.rows.length>200,sourceSheet:source.sourceSheet,sourceSpreadsheetId:source.sourceSpreadsheetId};}

function importRevenueSheet_(context){requireRole_(context,['ADMIN']);var source=readRevenueSource_();var sourceRows=source.rows;return withWriteLock_(function(){var executives=new SheetRepository_('executives').all();var byEmployee={};executives.forEach(function(row){byEmployee[String(row.employeeId).toUpperCase()]=row;});var missing=[];sourceRows.forEach(function(row){if(!byEmployee[String(row.employeeId).toUpperCase()])missing.push(row.employeeId);});if(missing.length)throw apiError_(400,'Unknown employee IDs in revenue connection: '+missing.slice(0,10).join(', '));var repo=new SheetRepository_('performance');var rows=repo.all();var byKey={};rows.forEach(function(row,index){byKey[String(row.periodType).toUpperCase()+'|'+dateOnly_(row.period)+'|'+row.executiveId]=index;});var stamp=now_();sourceRows.forEach(function(input){var executive=byEmployee[String(input.employeeId).toUpperCase()];var key=input.periodType+'|'+input.period+'|'+executive.id;var index=Object.prototype.hasOwnProperty.call(byKey,key)?byKey[key]:-1;var record={id:index>=0?rows[index].id:id_(),periodType:input.periodType,period:input.period,executiveId:executive.id,revenue:input.revenue,login:input.login,demo:input.demo,license:input.license,proPlatform:input.proPlatform,manualRevenue:input.manualRevenue,updatedAt:stamp,updatedBy:context.email};if(index>=0)rows[index]=record;else{byKey[key]=rows.length;rows.push(record);}});repo.replaceAll(rows);new SheetRepository_('sheetImports').insertMany([{id:id_(),type:'REVENUE_CONNECTION',fileName:source.sourceSheet,status:'SUCCESS',rowCount:sourceRows.length,errorCount:0,createdAt:stamp,createdBy:context.email}]);audit_(context,'performance','Connections','BULK_UPSERT','',null,{rowCount:sourceRows.length,sourceSheet:source.sourceSheet,sourceSpreadsheetId:source.sourceSpreadsheetId},'Connected revenue import',1);return{imported:sourceRows.length,total:rows.length,sourceSheet:source.sourceSheet,sourceSpreadsheetId:source.sourceSpreadsheetId};});}
