function SheetRepository_(name){if(!PLATFORM.SHEETS[name])throw new Error('Unknown repository: '+name);this.name=name;this.headers=PLATFORM.SHEETS[name];this.sheet=SpreadsheetApp.openById(requiredProperty_('SPREADSHEET_ID')).getSheetByName(name);if(!this.sheet)throw new Error('Run setupPlatform first. Missing sheet: '+name);}
SheetRepository_.prototype.all=function(){var last=this.sheet.getLastRow();if(last<2)return[];var values=this.sheet.getRange(2,1,last-1,this.headers.length).getValues();var headers=this.headers;return values.filter(function(row){return row.some(function(v){return v!=='';});}).map(function(row){var value={};headers.forEach(function(header,index){value[header]=serializeCell_(row[index]);});return value;});};
SheetRepository_.prototype.find=function(predicate){return this.all().filter(predicate);};
SheetRepository_.prototype.insertMany=function(records){if(!records.length)return[];var headers=this.headers;var normalized=records.map(function(record){return headers.map(function(header){return cellValue_(record[header]);});});this.sheet.getRange(this.sheet.getLastRow()+1,1,normalized.length,headers.length).setValues(normalized);return records;};
SheetRepository_.prototype.replaceAll=function(records){var last=this.sheet.getLastRow();if(last>1)this.sheet.getRange(2,1,last-1,this.headers.length).clearContent();if(records.length)this.sheet.getRange(2,1,records.length,this.headers.length).setValues(records.map(this.toRow_.bind(this)));return records;};
SheetRepository_.prototype.toRow_=function(record){return this.headers.map(function(header){return cellValue_(record[header]);});};
function serializeCell_(value){return value instanceof Date?value.toISOString():value;}
function cellValue_(value){if(value===undefined||value===null)return'';if(typeof value==='object')return safeJson_(value);return value;}
function ensureSheet_(spreadsheet,name,headers){var sheet=spreadsheet.getSheetByName(name)||spreadsheet.insertSheet(name);if(sheet.getMaxColumns()<headers.length)sheet.insertColumnsAfter(sheet.getMaxColumns(),headers.length-sheet.getMaxColumns());var current=sheet.getRange(1,1,1,headers.length).getValues()[0];if(current.join('|')!==headers.join('|')){if(sheet.getLastRow()>1&&current.some(String))throw new Error('Header mismatch on '+name+'. Preserve data and align headers before setup.');sheet.getRange(1,1,1,headers.length).setValues([headers]);}sheet.setFrozenRows(1);sheet.getRange(1,1,1,headers.length).setFontWeight('bold').setBackground('#e2e8f0');sheet.autoResizeColumns(1,headers.length);}
function withWriteLock_(callback){var lock=LockService.getScriptLock();lock.waitLock(30000);try{return callback();}finally{lock.releaseLock();}}
function audit_(context,sheet,module,action,recordId,oldValue,newValue,reason,version){new SheetRepository_('auditLogs').insertMany([{id:id_(),timestamp:now_(),user:context.email,sheet:sheet,module:module,action:action,recordId:recordId||'',oldValue:safeJson_(oldValue||null),newValue:safeJson_(newValue||null),reason:reason||'',version:version||'',correlationId:context.correlationId}]);}
