function SheetRepository_(name){if(!PLATFORM.SHEETS[name])throw new Error('Unknown repository: '+name);this.name=name;this.headers=PLATFORM.SHEETS[name];this.sheet=SpreadsheetApp.openById(requiredProperty_('SPREADSHEET_ID')).getSheetByName(name);if(!this.sheet)throw new Error('Run setupPlatform first. Missing sheet: '+name);ensureRepositoryHeaders_(this.sheet,this.headers,name);}
var REPOSITORY_CACHEABLE_={sources:true,executives:true,managerMappings:true,monthlyMappings:true,weeklyMappings:true,targetVersions:true,weeklyTargets:true,monthlyTargets:true,weeklySnapshots:true,monthlySnapshots:true,performance:true,weeklyIncentives:true,incentives:true,bonusRules:true,agentDataDump:true};
function repositoryCachePrefix_(name){return'ib-repository-v4:'+name;}
function repositoryCacheRead_(name){if(!REPOSITORY_CACHEABLE_[name])return null;var cache=CacheService.getScriptCache();var prefix=repositoryCachePrefix_(name);var metaText=cache.get(prefix+':meta');if(!metaText)return null;try{var meta=JSON.parse(metaText);var keys=[];for(var index=0;index<meta.chunks;index++)keys.push(prefix+':'+index);var chunks=cache.getAll(keys);var serialized='';for(var chunkIndex=0;chunkIndex<keys.length;chunkIndex++){if(!Object.prototype.hasOwnProperty.call(chunks,keys[chunkIndex]))return null;serialized+=chunks[keys[chunkIndex]];}return JSON.parse(serialized);}catch(error){cache.remove(prefix+':meta');return null;}}
function repositoryCacheWrite_(name,records){if(!REPOSITORY_CACHEABLE_[name])return;var serialized=safeJson_(records);var chunkSize=20000;var chunks=Math.max(1,Math.ceil(serialized.length/chunkSize));if(chunks>100)return;var prefix=repositoryCachePrefix_(name);var entries={};for(var index=0;index<chunks;index++)entries[prefix+':'+index]=serialized.slice(index*chunkSize,(index+1)*chunkSize);entries[prefix+':meta']=safeJson_({chunks:chunks});CacheService.getScriptCache().putAll(entries,name==='agentDataDump'?21600:600);}
function repositoryCacheInvalidate_(name){if(!REPOSITORY_CACHEABLE_[name])return;var cache=CacheService.getScriptCache();var prefix=repositoryCachePrefix_(name);var metaText=cache.get(prefix+':meta');var keys=[prefix+':meta'];if(metaText){try{var chunks=Number(JSON.parse(metaText).chunks)||0;for(var index=0;index<chunks;index++)keys.push(prefix+':'+index);}catch(error){console.warn('Unable to parse repository cache metadata for '+name);}}cache.removeAll(keys);}
SheetRepository_.prototype.all=function(){var cached=repositoryCacheRead_(this.name);if(cached!==null)return cached;var last=this.sheet.getLastRow();if(last<2){repositoryCacheWrite_(this.name,[]);return[];}var values=this.sheet.getRange(2,1,last-1,this.headers.length).getValues();var headers=this.headers;var records=values.filter(function(row){return row.some(function(v){return v!=='';});}).map(function(row){var value={};headers.forEach(function(header,index){value[header]=serializeCell_(row[index],header);});return value;});repositoryCacheWrite_(this.name,records);return records;};
SheetRepository_.prototype.find=function(predicate){return this.all().filter(predicate);};
SheetRepository_.prototype.insertMany=function(records){if(!records.length)return[];var headers=this.headers;var normalized=records.map(function(record){return headers.map(function(header){return cellValue_(record[header]);});});var start=this.sheet.getLastRow()+1;this.formatSemanticText_(start,normalized.length);this.sheet.getRange(start,1,normalized.length,headers.length).setValues(normalized);repositoryCacheInvalidate_(this.name);return records;};
SheetRepository_.prototype.replaceAll=function(records){var last=this.sheet.getLastRow();if(last>1)this.sheet.getRange(2,1,last-1,this.headers.length).clearContent();if(records.length){this.formatSemanticText_(2,records.length);this.sheet.getRange(2,1,records.length,this.headers.length).setValues(records.map(this.toRow_.bind(this)));}repositoryCacheInvalidate_(this.name);return records;};
SheetRepository_.prototype.toRow_=function(record){return this.headers.map(function(header){return cellValue_(record[header]);});};
SheetRepository_.prototype.formatSemanticText_=function(startRow,rowCount){var sheet=this.sheet;var ranges=[];this.headers.forEach(function(header,index){if(isCalendarHeader_(header))ranges.push(sheet.getRange(startRow,index+1,rowCount,1).getA1Notation());});if(ranges.length)sheet.getRangeList(ranges).setNumberFormat('@');};
function isMonthHeader_(header){return['month','dataMonth','data_month'].indexOf(String(header))>=0;}
function isDateHeader_(header){return['doj','effectiveFrom','effectiveTo','weekStart','period'].indexOf(String(header))>=0;}
function isCalendarHeader_(header){return isMonthHeader_(header)||isDateHeader_(header);}
function serializeCell_(value,header){if(!(value instanceof Date))return value;if(isMonthHeader_(header))return monthOnly_(value);if(isDateHeader_(header))return dateOnly_(value);return value.toISOString();}
function cellValue_(value){if(value===undefined||value===null)return'';if(typeof value==='object')return safeJson_(value);return value;}
function ensureRepositoryHeaders_(sheet,headers,name){var currentWidth=Math.max(1,sheet.getLastColumn());var current=sheet.getRange(1,1,1,Math.min(currentWidth,headers.length)).getValues()[0];var populated=current.filter(String).length;if(populated===headers.length&&current.join('|')===headers.join('|'))return;if(populated<headers.length&&current.slice(0,populated).join('|')===headers.slice(0,populated).join('|')){sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);return;}throw new Error('Header mismatch on '+name+'. Preserve data and align headers before continuing.');}
function ensureSheet_(spreadsheet,name,headers){var sheet=spreadsheet.getSheetByName(name)||spreadsheet.insertSheet(name);if(sheet.getMaxColumns()<headers.length)sheet.insertColumnsAfter(sheet.getMaxColumns(),headers.length-sheet.getMaxColumns());var current=sheet.getRange(1,1,1,headers.length).getValues()[0];if(current.join('|')!==headers.join('|')){var populated=current.filter(String).length;var appendOnly=populated<headers.length&&current.slice(0,populated).join('|')===headers.slice(0,populated).join('|');if(sheet.getLastRow()>1&&current.some(String)&&!appendOnly)throw new Error('Header mismatch on '+name+'. Preserve data and align headers before setup.');sheet.getRange(1,1,1,headers.length).setValues([headers]);}sheet.setFrozenRows(1);sheet.getRange(1,1,1,headers.length).setFontWeight('bold').setBackground('#e2e8f0');sheet.autoResizeColumns(1,headers.length);}
function withWriteLock_(callback){var lock=LockService.getScriptLock();lock.waitLock(30000);try{return callback();}finally{lock.releaseLock();}}
function audit_(context,sheet,module,action,recordId,oldValue,newValue,reason,version){new SheetRepository_('auditLogs').insertMany([{id:id_(),timestamp:now_(),user:context.email,sheet:sheet,module:module,action:action,recordId:recordId||'',oldValue:safeJson_(oldValue||null),newValue:safeJson_(newValue||null),reason:reason||'',version:version||'',correlationId:context.correlationId}]);}
