'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createColumnHelper } from '@tanstack/react-table';
import { Check, Clipboard, Download, Plus, RefreshCw, Search, X } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { DataTable } from '@/components/data-table';
import { api, Executive, MappingBatchInput, MappingCandidate, MappingOverride, MonthlyMapping } from '@/lib/api';
import { gasApi } from '@/lib/apps-script';
import { parsePaste } from '@/lib/paste-parser';

type NewAgent = Omit<MappingBatchInput['newExecutives'][number], 'selectedWeeks'>;
type Editable = { source: string; tenurity: string; status: string; selectedWeeks: string[] };
type ReviewEdit = { source: string; tenurity: string; selectedWeeks: string[] };
type AgentDumpRow = Pick<Executive, 'employeeId' | 'name' | 'email' | 'doj' | 'manager'> & { dataMonth: string };
type AgentSync = { refreshed: boolean; sourceSheet: string; rowCount?: number; reason: string; warning?: string };
type AgentPreview = { rows: AgentDumpRow[]; sourceSheet: string; sourceSpreadsheetId: string; availableMonths: string[]; sync?: AgentSync };
type ImportResult = { imported: number; mappingsCreated: number };

const currentMonth = new Date().toISOString().slice(0, 7);
const agentTemplate = 'Employee ID\tExecutive Name\tEmail\tDOJ\tManager\tSource\tTenurity\tStatus\nIB005\tAnanya Gupta\tananya@example.com\t2026-08-01\tRiya Kapoor\tInbound\tM0\tACTIVE';
const aliases: Record<keyof NewAgent, string[]> = { employeeId: ['Employee ID', 'EmployeeID'], name: ['Executive Name', 'Name', 'Agent'], email: ['Email'], doj: ['DOJ', 'Date of Joining'], manager: ['Manager'], source: ['Source'], tenurity: ['Tenurity', 'Tenure'], status: ['Status'] };
const localDateTime = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);
function weeksInMonth(month: string) { const result: string[] = []; const date = new Date(`${month}-01T00:00:00Z`); const day = date.getUTCDay(); date.setUTCDate(date.getUTCDate() - (day === 0 ? 6 : day - 1)); for (let index = 0; index < 6; index += 1) { const thursday = new Date(date); thursday.setUTCDate(thursday.getUTCDate() + 3); if (thursday.toISOString().slice(0, 7) === month) result.push(date.toISOString().slice(0, 10)); date.setUTCDate(date.getUTCDate() + 7); } return result; }
function toggleValue(values: string[], value: string) { return values.includes(value) ? values.filter((item) => item !== value) : [...values, value]; }

const column = createColumnHelper<MonthlyMapping>();
const columns = [
  column.accessor('month', { header: 'Month' }), column.accessor('employeeId', { header: 'Employee ID' }), column.accessor('name', { header: 'Executive' }),
  column.accessor('manager', { header: 'Manager' }), column.accessor('source', { header: 'Source' }), column.accessor('tenurity', { header: 'Tenurity' }),
  column.accessor('selectedWeeks', { header: 'Weeks', cell: (info) => `${info.getValue().length} selected` }), column.accessor('status', { header: 'Status' }),
];

function WeekSelector({ weeks, selected, onChange }: { weeks: string[]; selected: string[]; onChange: (weeks: string[]) => void }) {
  return <div className="flex flex-wrap gap-1.5">{weeks.map((week, index) => <label key={week} className={`cursor-pointer rounded-md border px-2 py-1 text-xs font-medium ${selected.includes(week) ? 'border-blue-300 bg-blue-50 text-blue-800' : 'border-slate-200 bg-white text-slate-500'}`}><input className="mr-1.5" type="checkbox" checked={selected.includes(week)} onChange={() => onChange(toggleValue(selected, week))} />W{index + 1}<span className="ml-1 hidden xl:inline">{week.slice(5)}</span></label>)}</div>;
}

export default function Page() {
  const auth = useAuth(); const queryClient = useQueryClient();
  const [month, setMonth] = useState(currentMonth); const weeks = useMemo(() => weeksInMonth(month), [month]);
  const [open, setOpen] = useState(false); const [tab, setTab] = useState<'existing' | 'paste' | 'connected'>('existing');
  const [selected, setSelected] = useState<string[]>([]); const [overrides, setOverrides] = useState<Record<string, Editable>>({});
  const [search, setSearch] = useState(''); const [pasted, setPasted] = useState(''); const [copied, setCopied] = useState(false); const [newWeeks, setNewWeeks] = useState<string[]>(weeks);
  const [dumpRows, setDumpRows] = useState<AgentDumpRow[]>([]); const [dumpSelected, setDumpSelected] = useState<string[]>([]); const [connectedSearch, setConnectedSearch] = useState('');
  const [connectedSource, setConnectedSource] = useState(''); const [connectedTenurity, setConnectedTenurity] = useState(''); const [connectedStatus, setConnectedStatus] = useState(''); const [connectedWeeks, setConnectedWeeks] = useState<string[]>(weeks);
  const [agentConnection, setAgentConnection] = useState<AgentPreview | null>(null); const [reviewing, setReviewing] = useState(false); const [pastedReview, setPastedReview] = useState<Record<string, ReviewEdit>>({}); const [connectedReview, setConnectedReview] = useState<Record<string, ReviewEdit>>({});
  const [confirmed, setConfirmed] = useState(false); const [notice, setNotice] = useState(''); const [fetchMessage, setFetchMessage] = useState('');

  const mappings = useQuery({ queryKey: ['monthly-mappings', month], enabled: Boolean(auth.session), queryFn: () => api<MonthlyMapping[]>(`/monthly-mappings?month=${month}`) });
  const candidates = useQuery({ queryKey: ['mapping-candidates', month], enabled: Boolean(auth.session), queryFn: () => api<MappingCandidate[]>(`/mapping-candidates?month=${month}`) });
  const parsed = useMemo(() => pasted.trim() ? parsePaste<NewAgent>(pasted, aliases, (row) => {
    if (!row.employeeId || !row.name || !row.email || !row.doj || !row.manager || !row.source || !row.tenurity) throw new Error('Required value is blank.');
    if (!/^\S+@\S+\.\S+$/.test(row.email)) throw new Error('Email is invalid.');
    const tenurity = row.tenurity.toUpperCase(); const status = (row.status || 'ACTIVE').toUpperCase();
    if (!['M0', 'M1', 'M1+'].includes(tenurity)) throw new Error('Tenurity must be M0, M1, or M1+.');
    if (!['ACTIVE', 'INACTIVE'].includes(status)) throw new Error('Status must be ACTIVE or INACTIVE.');
    return { ...row, tenurity, status };
  }) : { rows: [] as NewAgent[], errors: [] as string[] }, [pasted]);
  const filtered = useMemo(() => { const query = search.toLowerCase().trim(); return (candidates.data ?? []).filter((agent) => !query || [agent.employeeId, agent.name, agent.email, agent.manager, agent.suggestedSource, agent.suggestedTenurity].some((value) => String(value).toLowerCase().includes(query))); }, [candidates.data, search]);
  const filteredDump = useMemo(() => { const query = connectedSearch.toLowerCase().trim(); return dumpRows.filter((agent) => !query || [agent.employeeId, agent.name, agent.email, agent.manager].some((value) => String(value).toLowerCase().includes(query))); }, [dumpRows, connectedSearch]);
  const byEmployee = useMemo(() => new Map((candidates.data ?? []).map((row) => [row.employeeId.toUpperCase(), row])), [candidates.data]);
  const selectedConnectedRows = useMemo(() => dumpRows.filter((row) => dumpSelected.includes(row.employeeId)), [dumpRows, dumpSelected]);

  const save = useMutation({ mutationFn: (input: MappingBatchInput) => api<MonthlyMapping[]>('/monthly-mappings/batch', { method: 'POST', body: JSON.stringify(input) }), onSuccess: async (created) => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['monthly-mappings', month] }), queryClient.invalidateQueries({ queryKey: ['mapping-candidates', month] })]); setNotice(`${created.length} mapping${created.length === 1 ? '' : 's'} saved for ${month}.`); closeModal(); } });
  const fetchDump = useMutation({ mutationFn: () => gasApi<AgentPreview>('agents.dump.preview', { limit: 1000, month }), onSuccess: (data) => { setDumpRows(data.rows); setDumpSelected([]); setAgentConnection(data); } });
  const importDump = useMutation({ mutationFn: () => gasApi<ImportResult>('agents.dump.import', { employeeIds: dumpSelected, details: { status: connectedStatus || undefined, updatedAt: localDateTime() }, overrides: dumpSelected.map((employeeId) => ({ employeeId, source: connectedReview[employeeId]?.source, tenurity: connectedReview[employeeId]?.tenurity, selectedWeeks: connectedReview[employeeId]?.selectedWeeks })), selectedWeeks: connectedWeeks, month, limit: 10000 }), onSuccess: async (result) => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['monthly-mappings', month] }), queryClient.invalidateQueries({ queryKey: ['mapping-candidates', month] })]); setNotice(`Imported ${result.imported} executive${result.imported === 1 ? '' : 's'} and created ${result.mappingsCreated} mapping${result.mappingsCreated === 1 ? '' : 's'}.`); closeModal(); } });

  function closeModal() { setOpen(false); setSelected([]); setOverrides({}); setDumpSelected([]); setPasted(''); setReviewing(false); setPastedReview({}); setConnectedReview({}); setConfirmed(false); }
  function editFor(agent: MappingCandidate): Editable { return overrides[agent._id] ?? { source: '', tenurity: '', status: '', selectedWeeks: weeks }; }
  function edit(agent: MappingCandidate, value: Partial<Editable>) { setOverrides((current) => ({ ...current, [agent._id]: { ...editFor(agent), ...value } })); setConfirmed(false); }
  function toggleAgent(agent: MappingCandidate) { if (agent.alreadyMapped) return; setSelected((current) => current.includes(agent._id) ? current.filter((id) => id !== agent._id) : [...current, agent._id]); setConfirmed(false); }
  function submit(event: FormEvent) { event.preventDefault(); if (!reviewing || !confirmed || parsed.errors.length || !selected.length && !parsed.rows.length) return; const selectedOverrides: MappingOverride[] = selected.map((id) => ({ executiveId: id, ...overrides[id], selectedWeeks: overrides[id]?.selectedWeeks ?? weeks })); const reviewedNewExecutives = parsed.rows.map((row) => ({ ...row, source: pastedReview[row.employeeId]?.source ?? row.source, tenurity: pastedReview[row.employeeId]?.tenurity ?? row.tenurity, selectedWeeks: pastedReview[row.employeeId]?.selectedWeeks ?? newWeeks })); save.mutate({ month, executiveIds: selected, newExecutives: reviewedNewExecutives, overrides: selectedOverrides, defaultSelectedWeeks: newWeeks }); }
  async function refreshData() { setFetchMessage(''); const [mappingResult, candidateResult] = await Promise.all([mappings.refetch(), candidates.refetch()]); const error = mappingResult.error || candidateResult.error; setFetchMessage(error ? error.message : `Loaded ${mappingResult.data?.length ?? 0} mappings and ${candidateResult.data?.length ?? 0} agents.`); }
  async function copy() { await navigator.clipboard.writeText(agentTemplate); setCopied(true); setTimeout(() => setCopied(false), 1500); }
  function beginReview() {
    if (tab === 'paste') setPastedReview(Object.fromEntries(parsed.rows.map((row) => [row.employeeId, { source: row.source, tenurity: row.tenurity, selectedWeeks: newWeeks }])));
    if (tab === 'connected') setConnectedReview(Object.fromEntries(selectedConnectedRows.map((row) => { const existing = byEmployee.get(row.employeeId.toUpperCase()); return [row.employeeId, { source: connectedSource || existing?.suggestedSource || '', tenurity: connectedTenurity || existing?.suggestedTenurity || '', selectedWeeks: connectedWeeks }]; })));
    setConfirmed(false); setReviewing(true);
  }
  const reviewInvalid = reviewing && (tab === 'existing'
    ? selected.some((id) => { const agent = (candidates.data ?? []).find((row) => row._id === id); return !agent || !(overrides[id]?.source || agent.suggestedSource) || !(overrides[id]?.tenurity || agent.suggestedTenurity); })
    : tab === 'paste' ? parsed.rows.some((row) => !pastedReview[row.employeeId]?.source || !pastedReview[row.employeeId]?.tenurity)
      : dumpSelected.some((employeeId) => !connectedReview[employeeId]?.source || !connectedReview[employeeId]?.tenurity));
  const canReview = tab === 'connected' ? dumpSelected.length > 0 : selected.length + parsed.rows.length > 0 && !parsed.errors.length;
  const pending = save.isPending || importDump.isPending;

  return <>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Monthly executive mapping</h2><p className="text-slate-500">Choose agents, apply monthly changes, and select exactly which weeks participate.</p></div><div className="flex items-center gap-3"><label className="text-sm font-medium">Month <input type="month" className="ml-2" value={month} onChange={(event) => { setMonth(event.target.value); setOverrides({}); setSelected([]); setDumpSelected([]); setNewWeeks(weeksInMonth(event.target.value)); setConnectedWeeks(weeksInMonth(event.target.value)); }} /></label><button className="btn-secondary gap-2" onClick={() => void refreshData()} disabled={mappings.isFetching || candidates.isFetching}><RefreshCw size={16} className={mappings.isFetching || candidates.isFetching ? 'animate-spin' : ''} />Fetch</button>{auth.canWrite && <button className="btn gap-2" onClick={() => setOpen(true)}><Plus size={17} />Batch add</button>}</div></div>
    {notice && <p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}{fetchMessage && <p className="mb-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{fetchMessage}</p>}
    {(mappings.error || candidates.error) && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{(mappings.error || candidates.error)?.message}</p>}
    <DataTable data={mappings.data ?? []} columns={columns} isLoading={mappings.isLoading} emptyMessage={`No mappings found for ${month}.`} />

    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-2 sm:p-4"><form onSubmit={submit} className="flex max-h-[96vh] w-full max-w-7xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl">
      <header className="flex items-start justify-between border-b px-5 py-4"><div><div className="flex items-center gap-2"><h3 className="text-xl font-bold">Add monthly agent mappings</h3><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">{month}</span></div><p className="text-xs text-slate-500">Previous Source, Tenurity, and Status remain unchanged unless you override them.</p></div><button type="button" onClick={closeModal} className="rounded p-1 hover:bg-slate-100"><X size={20} /></button></header>
      {!reviewing && <div className={`grid ${auth.isAdmin ? 'grid-cols-3' : 'grid-cols-2'} gap-1 bg-slate-100 p-1.5`}>{(['existing', 'paste'] as const).map((value) => <button key={value} type="button" className={tab === value ? 'btn' : 'btn-secondary'} onClick={() => { setTab(value); setConfirmed(false); }}>{value === 'existing' ? `Existing agents (${selected.length})` : `Paste new (${parsed.rows.length})`}</button>)}{auth.isAdmin && <button type="button" className={tab === 'connected' ? 'btn' : 'btn-secondary'} onClick={() => { setTab('connected'); setConfirmed(false); }}>Connected sheet ({dumpSelected.length})</button>}</div>}
      <main className="min-h-0 flex-1 overflow-auto p-4">
        {!reviewing && tab === 'existing' && <div className="rounded-xl border"><div className="flex flex-wrap items-center justify-between gap-2 border-b bg-slate-50 p-3"><div><b>Agent directory</b><p className="text-xs text-slate-500">{filtered.length} shown · {selected.length} selected</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-2.5 top-2.5 text-slate-400" size={15} /><input className="w-80 py-1.5 pl-8" placeholder="Search agent, ID, manager or source" value={search} onChange={(event) => setSearch(event.target.value)} /></label><button type="button" className="btn-secondary py-1.5" onClick={() => { const ids = filtered.filter((row) => !row.alreadyMapped).map((row) => row._id); setSelected(ids.every((id) => selected.includes(id)) ? selected.filter((id) => !ids.includes(id)) : Array.from(new Set([...selected, ...ids]))); }}>Select visible</button></div></div>
          <div className="max-h-[58vh] overflow-auto">{filtered.map((agent) => { const value = editFor(agent); const checked = selected.includes(agent._id); return <div key={agent._id} className={`border-b p-3 last:border-0 ${checked ? 'bg-blue-50/40' : ''}`}><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3"><input type="checkbox" checked={checked || agent.alreadyMapped} disabled={agent.alreadyMapped} onChange={() => toggleAgent(agent)} /><div><b>{agent.name}</b><span className="ml-2 font-mono text-xs font-semibold text-blue-700">{agent.employeeId}</span><p className="text-xs text-slate-500">{agent.email} · {agent.manager || 'Manager missing'} · Previous month: {agent.previousMonth || 'first mapping'}</p></div>{agent.alreadyMapped && <span className="text-xs font-semibold text-emerald-700">Already mapped</span>}</div>{checked && <div className="mt-3 grid gap-2 pl-7 xl:grid-cols-[1fr_150px_160px_2fr]"><input list="source-options" placeholder={`Keep source: ${agent.suggestedSource || 'required'}`} value={value.source} onChange={(event) => edit(agent, { source: event.target.value })} /><select value={value.tenurity} onChange={(event) => edit(agent, { tenurity: event.target.value })}><option value="">Auto: {agent.suggestedTenurity}</option><option>M0</option><option>M1</option><option>M1+</option></select><select value={value.status} onChange={(event) => edit(agent, { status: event.target.value })}><option value="">Keep: {agent.suggestedStatus}</option><option>ACTIVE</option><option>INACTIVE</option></select><WeekSelector weeks={weeks} selected={value.selectedWeeks} onChange={(selectedWeeks) => edit(agent, { selectedWeeks })} /></div>}</div>; })}</div></div>}

        {!reviewing && tab === 'paste' && <div><div className="flex items-center justify-between"><p className="text-sm text-slate-600">Paste a header row and one or more tab-separated executive rows.</p><button type="button" className="btn-secondary gap-2" onClick={copy}>{copied ? <Check size={16} /> : <Clipboard size={16} />}{copied ? 'Copied' : 'Copy template'}</button></div><textarea className="mt-3 h-56 w-full rounded-lg border p-3 font-mono text-xs" placeholder={agentTemplate} value={pasted} onChange={(event) => { setPasted(event.target.value); setConfirmed(false); }} /><p className="mt-2 text-sm text-emerald-700">{parsed.rows.length} valid row{parsed.rows.length === 1 ? '' : 's'}</p>{parsed.errors.map((error) => <p key={error} className="text-sm text-red-700">{error}</p>)}<div className="mt-4 rounded-lg border bg-slate-50 p-3"><b className="text-sm">Weeks for pasted agents</b><div className="mt-2"><WeekSelector weeks={weeks} selected={newWeeks} onChange={(value) => { setNewWeeks(value); setConfirmed(false); }} /></div></div></div>}

        {!reviewing && tab === 'connected' && auth.isAdmin && <div><div className="flex items-start justify-between gap-3"><div><b>Connected executive identities</b><p className="text-sm text-slate-500">Identity fields come from the connected sheet. Existing operational values are preserved unless entered below.</p>{agentConnection && <p className="text-xs text-emerald-700">Connected to {agentConnection.sourceSheet} · {agentConnection.availableMonths.join(', ') || 'unversioned data'}</p>}</div><button type="button" className="btn-secondary gap-2" disabled={fetchDump.isPending} onClick={() => fetchDump.mutate()}><Download size={16} />{fetchDump.isPending ? 'Fetching…' : 'Fetch active agents'}</button></div>{fetchDump.error && <p className="mt-2 text-sm text-red-700">{fetchDump.error.message}</p>}
          {dumpRows.length > 0 && <div className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-xl border"><div className="flex items-center justify-between border-b bg-slate-50 p-3"><b>{filteredDump.length} available · {dumpSelected.length} selected</b><label className="relative"><Search className="absolute left-2.5 top-2.5 text-slate-400" size={15} /><input className="w-72 py-1.5 pl-8" placeholder="Search connected agents" value={connectedSearch} onChange={(event) => setConnectedSearch(event.target.value)} /></label></div><div className="max-h-[52vh] overflow-auto">{filteredDump.map((row) => <label key={row.employeeId} className="grid cursor-pointer grid-cols-[auto_1fr_auto] items-center gap-3 border-b p-3 last:border-0 hover:bg-blue-50"><input type="checkbox" checked={dumpSelected.includes(row.employeeId)} onChange={() => { setDumpSelected((current) => toggleValue(current, row.employeeId)); setConfirmed(false); }} /><span><b>{row.name}</b><span className="ml-2 font-mono text-xs text-blue-700">{row.employeeId}</span><span className="block text-xs text-slate-500">{row.email} · {row.manager}</span></span><span className="text-xs text-slate-400">{row.dataMonth || 'No month'}</span></label>)}</div></div>
            <aside className="h-fit rounded-xl border bg-slate-50 p-3"><b>Optional batch defaults</b><p className="mb-3 text-xs text-slate-500">These prefill the final review. You can still change Source and Tenurity for each selected agent there.</p><div className="grid gap-2"><input placeholder="Keep previous source" value={connectedSource} onChange={(event) => { setConnectedSource(event.target.value); setConfirmed(false); }} /><select value={connectedTenurity} onChange={(event) => { setConnectedTenurity(event.target.value); setConfirmed(false); }}><option value="">Auto / keep tenurity</option><option>M0</option><option>M1</option><option>M1+</option></select><select value={connectedStatus} onChange={(event) => { setConnectedStatus(event.target.value); setConfirmed(false); }}><option value="">Keep status / ACTIVE for new</option><option>ACTIVE</option><option>INACTIVE</option></select></div><b className="mt-4 block text-sm">Weeks</b><div className="mt-2"><WeekSelector weeks={weeks} selected={connectedWeeks} onChange={(value) => { setConnectedWeeks(value); setConfirmed(false); }} /></div></aside></div>}
        </div>}

        {reviewing && <div><div className="mb-3"><h4 className="text-lg font-bold">Final agent review</h4><p className="text-sm text-slate-500">Verify every selected agent. Source and Tenurity can be corrected here before confirmation.</p></div><div className="overflow-auto rounded-xl border"><table className="min-w-[920px] text-sm"><thead className="sticky top-0 z-10 bg-slate-100"><tr><th>Employee ID</th><th>Executive</th><th>Source</th><th>Tenurity</th><th>Status</th><th>Weeks</th></tr></thead><tbody>
          {tab === 'existing' && selected.map((id) => { const agent = (candidates.data ?? []).find((row) => row._id === id); if (!agent) return null; const value = editFor(agent); return <tr key={id}><td className="font-mono font-semibold text-blue-700">{agent.employeeId}</td><td><b>{agent.name}</b><span className="block text-xs text-slate-500">{agent.email}</span></td><td><input aria-label={`${agent.employeeId} Source`} value={value.source || agent.suggestedSource} onChange={(event) => edit(agent, { source: event.target.value })} /></td><td><select aria-label={`${agent.employeeId} Tenurity`} value={value.tenurity || agent.suggestedTenurity} onChange={(event) => edit(agent, { tenurity: event.target.value })}><option>M0</option><option>M1</option><option>M1+</option></select></td><td>{value.status || agent.suggestedStatus}</td><td><WeekSelector weeks={weeks} selected={value.selectedWeeks} onChange={(selectedWeeks) => edit(agent, { selectedWeeks })} /></td></tr>; })}
          {tab === 'paste' && parsed.rows.map((agent) => { const value = pastedReview[agent.employeeId] ?? { source: agent.source, tenurity: agent.tenurity, selectedWeeks: newWeeks }; return <tr key={agent.employeeId}><td className="font-mono font-semibold text-blue-700">{agent.employeeId}</td><td><b>{agent.name}</b><span className="block text-xs text-slate-500">{agent.email}</span></td><td><input aria-label={`${agent.employeeId} Source`} value={value.source} onChange={(event) => { setPastedReview((current) => ({ ...current, [agent.employeeId]: { ...value, source: event.target.value } })); setConfirmed(false); }} /></td><td><select aria-label={`${agent.employeeId} Tenurity`} value={value.tenurity} onChange={(event) => { setPastedReview((current) => ({ ...current, [agent.employeeId]: { ...value, tenurity: event.target.value } })); setConfirmed(false); }}><option>M0</option><option>M1</option><option>M1+</option></select></td><td>{agent.status || 'ACTIVE'}</td><td><WeekSelector weeks={weeks} selected={value.selectedWeeks} onChange={(selectedWeeks) => { setPastedReview((current) => ({ ...current, [agent.employeeId]: { ...value, selectedWeeks } })); setConfirmed(false); }} /></td></tr>; })}
          {tab === 'connected' && selectedConnectedRows.map((agent) => { const value = connectedReview[agent.employeeId] ?? { source: '', tenurity: '', selectedWeeks: connectedWeeks }; const existing = byEmployee.get(agent.employeeId.toUpperCase()); return <tr key={agent.employeeId}><td className="font-mono font-semibold text-blue-700">{agent.employeeId}</td><td><b>{agent.name}</b><span className="block text-xs text-slate-500">{agent.email}</span></td><td><input aria-label={`${agent.employeeId} Source`} placeholder="Source required" value={value.source} onChange={(event) => { setConnectedReview((current) => ({ ...current, [agent.employeeId]: { ...value, source: event.target.value } })); setConfirmed(false); }} /></td><td><select aria-label={`${agent.employeeId} Tenurity`} value={value.tenurity} onChange={(event) => { setConnectedReview((current) => ({ ...current, [agent.employeeId]: { ...value, tenurity: event.target.value } })); setConfirmed(false); }}><option value="">Select tenurity</option><option>M0</option><option>M1</option><option>M1+</option></select></td><td>{connectedStatus || existing?.suggestedStatus || 'ACTIVE'}</td><td><WeekSelector weeks={weeks} selected={value.selectedWeeks} onChange={(selectedWeeks) => { setConnectedReview((current) => ({ ...current, [agent.employeeId]: { ...value, selectedWeeks } })); setConfirmed(false); }} /></td></tr>; })}
        </tbody></table></div>{reviewInvalid && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">Every reviewed agent must have a Source and Tenurity before confirmation.</p>}</div>}
      </main>
      <footer className="border-t bg-white p-4">{reviewing && <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><b>Final confirmation:</b> this creates a frozen {month} mapping. Source and Tenurity shown above are the values that will be stored. Unselected weeks remain blank and do not contribute to incentives.<label className="mt-2 flex items-start gap-2 font-semibold"><input type="checkbox" checked={confirmed} disabled={reviewInvalid} onChange={(event) => setConfirmed(event.target.checked)} />I reviewed each agent’s Source, Tenurity, status, and selected weeks.</label></div>}{(save.error || importDump.error) && <p className="mt-2 text-sm text-red-700">{(save.error || importDump.error)?.message}</p>}<div className="mt-3 flex items-center justify-between"><p className="text-sm font-medium">{tab === 'connected' ? dumpSelected.length : selected.length + parsed.rows.length} agent{(tab === 'connected' ? dumpSelected.length : selected.length + parsed.rows.length) === 1 ? '' : 's'} selected</p><div className="flex gap-2"><button type="button" className="btn-secondary" onClick={reviewing ? () => { setReviewing(false); setConfirmed(false); } : closeModal}>{reviewing ? 'Back to edit' : 'Cancel'}</button>{!reviewing ? <button type="button" className="btn" disabled={!canReview} onClick={beginReview}>Review selected agents</button> : tab === 'connected' ? <button type="button" className="btn" disabled={!confirmed || reviewInvalid || pending} onClick={() => importDump.mutate()}>{pending ? 'Saving…' : 'Confirm and save'}</button> : <button className="btn" disabled={!confirmed || reviewInvalid || pending}>{pending ? 'Saving…' : 'Confirm and save'}</button>}</div></div></footer>
      <datalist id="source-options" />
    </form></div>}
  </>;
}
