'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createColumnHelper } from '@tanstack/react-table';
import { Check, Clipboard, Plus, X } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { api, Executive, MappingBatchInput, MonthlyMapping } from '@/lib/api';
import { parsePaste } from '@/lib/paste-parser';
import { DataTable } from '@/components/data-table';

type NewAgent = MappingBatchInput['newExecutives'][number];
const column = createColumnHelper<MonthlyMapping>();
const columns = [column.accessor('month',{header:'Month'}),column.accessor('employeeId',{header:'Employee ID'}),column.accessor('name',{header:'Executive'}),column.accessor('email',{header:'Email'}),column.accessor('manager',{header:'Manager'}),column.accessor('source',{header:'Source'}),column.accessor('tenurity',{header:'Tenurity'}),column.accessor('status',{header:'Status'})];
const currentMonth = new Date().toISOString().slice(0,7);
const agentTemplate = 'Employee ID\tExecutive Name\tEmail\tDOJ\tManager\tSource\tStatus\nIB005\tAnanya Gupta\tananya@example.com\t2026-08-01\tRiya Kapoor\tInbound\tACTIVE';
const aliases: Record<keyof NewAgent,string[]> = { employeeId:['Employee ID','EmployeeID'],name:['Executive Name','Name','Agent'],email:['Email'],doj:['DOJ','Date of Joining'],manager:['Manager'],source:['Source'],status:['Status'] };

export default function Page(){
  const[month,setMonth]=useState(currentMonth);const[open,setOpen]=useState(false);const[tab,setTab]=useState<'existing'|'paste'>('existing');const[selected,setSelected]=useState<string[]>([]);const[pasted,setPasted]=useState('');const[copied,setCopied]=useState(false);const queryClient=useQueryClient();
  const mappings=useQuery({queryKey:['monthly-mappings',month],queryFn:()=>api<MonthlyMapping[]>(`/monthly-mappings?month=${month}`)});const executives=useQuery({queryKey:['executives'],queryFn:()=>api<Executive[]>('/executives')});
  const parsed=useMemo(()=>parsePaste<NewAgent>(pasted,aliases,(row)=>{if(!row.employeeId||!row.name||!row.email||!row.doj||!row.manager||!row.source)throw new Error('Required value is blank.');if(!/^\S+@\S+\.\S+$/.test(row.email))throw new Error('Email is invalid.');if(Number.isNaN(new Date(row.doj).valueOf()))throw new Error('DOJ must be YYYY-MM-DD.');const status=row.status.toUpperCase();if(!['ACTIVE','INACTIVE'].includes(status))throw new Error('Status must be ACTIVE or INACTIVE.');return{...row,status};}),[pasted]);
  const save=useMutation({mutationFn:(input:MappingBatchInput)=>api('/monthly-mappings/batch',{method:'POST',body:JSON.stringify(input)}),onSuccess:async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:['monthly-mappings',month]}),queryClient.invalidateQueries({queryKey:['executives']})]);setOpen(false);setSelected([]);setPasted('');}});
  function toggle(id:string){setSelected((current)=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);}function submit(event:FormEvent){event.preventDefault();if(parsed.errors.length)return;save.mutate({month,executiveIds:selected,newExecutives:parsed.rows});}async function copy(){await navigator.clipboard.writeText(agentTemplate);setCopied(true);setTimeout(()=>setCopied(false),1500);}
  const alreadyMapped=new Set((mappings.data??[]).map(row=>row._id));
  return <><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Monthly executive mapping</h2><p className="text-slate-500">Batch-map existing agents or paste new profiles for a month-specific snapshot.</p></div><div className="flex items-center gap-3"><label className="text-sm font-medium">Month <input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="ml-2"/></label><button className="btn gap-2" onClick={()=>setOpen(true)}><Plus size={17}/> Batch add</button></div></div>{mappings.error&&<p className="mb-4 text-red-700">{mappings.error.message}</p>}<DataTable data={mappings.data??[]} columns={columns}/>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h3 className="text-xl font-bold">Batch add agents for {month}</h3><p className="text-sm text-slate-500">Combine selected existing agents with pasted new-agent rows.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="my-5 grid grid-cols-2 gap-2 rounded-lg bg-slate-100 p-1"><button type="button" className={tab==='existing'?'btn':'btn-secondary'} onClick={()=>setTab('existing')}>Existing agents ({selected.length})</button><button type="button" className={tab==='paste'?'btn':'btn-secondary'} onClick={()=>setTab('paste')}>Paste new agents ({parsed.rows.length})</button></div>
  {tab==='existing'?<div className="max-h-80 overflow-auto rounded-lg border">{executives.data?.map(agent=><label key={agent._id} className="flex cursor-pointer items-center gap-3 border-b p-3 last:border-0 hover:bg-slate-50"><input type="checkbox" checked={selected.includes(agent._id)||alreadyMapped.has(agent._id)} disabled={alreadyMapped.has(agent._id)} onChange={()=>toggle(agent._id)}/><span className="flex-1"><b>{agent.employeeId} — {agent.name}</b><span className="block text-xs text-slate-500">{agent.source} · {agent.manager} · {agent.status}</span></span>{alreadyMapped.has(agent._id)&&<span className="text-xs text-emerald-700">Already mapped</span>}</label>)}</div>:<div><div className="mb-2 flex items-center justify-between"><p className="text-sm text-slate-600">Paste tab-separated cells from Sheets/Excel, including the header row.</p><button type="button" className="btn-secondary gap-2" onClick={copy}>{copied?<Check size={16}/>:<Clipboard size={16}/>} {copied?'Copied':'Copy template'}</button></div><textarea className="h-52 w-full rounded-lg border p-3 font-mono text-xs" placeholder={agentTemplate} value={pasted} onChange={e=>setPasted(e.target.value)}/><div className="mt-2 text-sm"><span className="text-emerald-700">{parsed.rows.length} valid rows</span>{parsed.errors.map(error=><p key={error} className="text-red-700">{error}</p>)}</div></div>}
  {save.error&&<p className="mt-4 text-sm text-red-700">{save.error.message}</p>}<div className="mt-6 flex items-center justify-between"><p className="text-sm font-medium">Total to add: {selected.length+parsed.rows.length}</p><div className="flex gap-3"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn" disabled={save.isPending||!!parsed.errors.length||selected.length+parsed.rows.length===0}>{save.isPending?'Saving batch…':'Save batch'}</button></div></div></form></div>}</>;
}
